[
  "Comer, no comemos, pero reímos mucho.",
  "Estudiar, estudiamos poco, pero aprendemos rápido.",
  "Salir, no salimos, pero soñamos con viajar.",
  "Dormir, dormimos mal, pero descansamos.",
  "Ir, no vamos mucho, pero lo intentamos.",
  "Ganar, no ganamos siempre, pero competimos.",
  "Ver, vemos poco, pero lo entendemos todo.",
  "Llorar, lloramos a veces, pero seguimos.",
  "Trabajar, trabajamos mucho, pero felices.",
  "Leer, no leemos tanto, pero escribimos bien.",
  "Viajar, viajamos poco, pero aprendemos mucho.",
  "Reír, reímos cada día, eso sí.",
  "Escuchar, escuchamos poco, pero hablamos mucho.",
  "Pintar, no pintamos bien, pero lo intentamos.",
  "Cantar, cantamos mal, pero con alegría.",
  "Pensar, pensamos mucho, actuar menos.",
  "Jugar, no jugamos tanto, pero observamos.",
  "Soñar, soñamos despiertos, eso sí.",
  "Bailar, bailamos feo, pero con ritmo.",
  "Enseñar, enseñamos con amor, eso seguro.",
  "Aprender, aprendemos lento, pero firme.",
  "Hablar, no hablamos tanto, pero sentimos.",
  "Cocinar, cocinamos simple, pero sabroso.",
  "Caminar, caminamos lejos, sin quejarnos.",
  "Perder, perdemos seguido, pero no nos rendimos.",
  "Construir, construimos poco, pero sólido.",
  "Juzgar, no juzgamos, pero observamos.",
  "Olvidar, olvidamos a veces, pero recordamos lo importante.",
  "Esperar, esperamos poco, pero confiamos.",
  "Contar, contamos historias, aunque cortas.",
  "Nadar, nadamos mal, pero sin miedo.",
  "Escribir, escribimos lento, pero claro.",
  "Dudar, dudamos mucho, pero decidimos.",
  "Ayudar, ayudamos siempre que podemos.",
  "Resolver, resolvemos despacio, pero bien.",
  "Temer, tememos poco, confiamos mucho.",
  "Volver, volvemos tarde, pero volvemos.",
  "Vivir, vivimos intensamente.",
  "Compartir, compartimos siempre lo que hay.",
  "Aceptar, aceptamos todo, menos la injusticia.",
  "Criticar, criticamos poco, reflexionamos más.",
  "Lograr, logramos poco, pero con esfuerzo.",
  "Buscar, buscamos mucho, encontramos poco.",
  "Cuidar, cuidamos lo nuestro, lo ajeno también.",
  "Huir, no huimos, enfrentamos.",
  "Mentir, no mentimos, callamos.",
  "Recordar, recordamos todo, menos lo trivial.",
  "Obedecer, obedecemos, aunque con dudas.",
  "Elegir, elegimos mal, pero aprendemos.",
  "Confiar, confiamos de más, quizás.",
  "Perdonar, perdonamos, aunque cuesta.",
  "Discutir, discutimos, pero sin dañar.",
  "Luchar, luchamos callados.",
  "Negar, negamos poco, aceptamos mucho.",
  "Viajar, viajamos más en sueños.",
  "Temer, tememos lo justo.",
  "Mirar, miramos con atención.",
  "Descansar, descansamos mal, pero resistimos.",
  "Seguir, seguimos siempre adelante.",
  "Conocer, conocemos poco, pero nos abrimos.",
  "Creer, creemos siempre en algo.",
  "Soportar, soportamos mucho, quizá demasiado.",
  "Alabar, alabamos lo simple.",
  "Caer, caemos, pero nos levantamos.",
  "Buscar, buscamos sentido a todo.",
  "Responder, respondemos con cautela.",
  "Dudar, dudamos porque pensamos.",
  "Olvidar, olvidamos para avanzar.",
  "Abrazar, abrazamos poco, pero de corazón.",
  "Cerrar, cerramos ciclos con dolor.",
  "Abrir, abrimos el alma, no la boca.",
  "Guiar, guiamos desde el ejemplo.",
  "Aceptar, aceptamos la realidad.",
  "Imaginar, imaginamos futuros.",
  "Medir, medimos consecuencias.",
  "Temer, tememos perder lo amado.",
  "Luchar, luchamos sin descanso.",
  "Observar, observamos silencios.",
  "Entender, entendemos miradas.",
  "Tocar, tocamos corazones.",
  "Sentir, sentimos más de lo que decimos.",
  "Actuar, actuamos con ética.",
  "Cambiar, cambiamos lentamente.",
  "Resistir, resistimos con fe.",
  "Crecer, crecemos con el dolor.",
  "Insistir, insistimos por justicia.",
  "Valorar, valoramos lo vivido.",
  "Responder, respondemos sin gritar.",
  "Aceptar, aceptamos lo distinto.",
  "Compartir, compartimos alegrías.",
  "Soñar, soñamos despiertos.",
  "Permanecer, permanecemos por amor.",
  "Aprender, aprendemos del error.",
  "Ayudar, ayudamos en silencio.",
  "Decidir, decidimos sin miedo.",
  "Conectar, conectamos desde la emoción.",
  "Leer, leemos con los ojos del alma.",
  "Volver, volvemos con gratitud.",
  "Confiar, confiamos con reservas.",
  "Reflexionar, reflexionamos antes de actuar.",
  "Expresar, expresamos sin miedo.",
  "Disfrutar, disfrutamos los pequeños momentos.",
  "Acompañar, acompañamos sin invadir."
]
