# Lista de oraciones activas, pasivas y sus traducciones al inglés
oraciones_activas = [
    "1. Los desarrolladores crean aplicaciones eficientes en Python.",
    "2. Python facilita un código limpio y legible.",
    "3. Muchos programadores eligen Python por su versatilidad.",
    "4. Las empresas utilizan Python para desarrollar aplicaciones web.",
    "5. Python ofrece una gran cantidad de bibliotecas útiles.",
    "6. Los principiantes aprenden Python con rapidez.",
    "7. Los científicos de datos utilizan Python en sus investigaciones.",
    "8. Python simplifica la creación de scripts automatizados.",
    "9. Los ingenieros de software prefieren Python para proyectos complejos.",
    "10. Python acelera el desarrollo de proyectos de inteligencia artificial.",
    "11. Los estudiantes aprenden a programar en Python en sus cursos de informática.",
    "12. Las universidades incluyen Python en sus planos de estudio.",
    "13. Python permite a los programadores resolver problemas matemáticos complejos.",
    "14. Los diseñadores de videojuegos utilizan Python para prototipos rápidos.",
    "15. Los desarrolladores escriben aplicaciones móviles con Python.",
    "16. Python soporta el desarrollo de software en múltiples plataformas.",
    "17. Python facilita la interacción con bases de datos.",
    "18. Las empresas de tecnología invierten en proyectos desarrollados en Python.",
    "19. Python ayuda a los ingenieros a realizar simulaciones.",
    "20. Los investigadores utilizan Python para análisis de datos masivos.",
    "21. Python es compatible con herramientas de visualización de datos.",
    "22. Los programadores crean servidores web con frameworks de Python.",
    "23. Python mejora el rendimiento de aplicaciones de procesamiento de datos.",
    "24. Los expertos en seguridad informática implementan herramientas en Python.",
    "25. Python permite a los desarrolladores integrar servicios en la nube.",
    "26. Los matemáticos modelan ecuaciones complejas con Python.",
    "27. Python soporta el desarrollo de aplicaciones de interfaz gráfica de usuario.",
    "28. Los programadores automatizan tareas repetitivas con Python.",
    "29. Python acelera la creación de programas científicos.",
    "30. Los ingenieros de datos limpian y transforman datos con Python.",
    "31. Python permite a los analistas de datos realizar consultas en grandes bases de datos.",
    "32. Los investigadores en biotecnología analizan secuencias genéticas con Python.",
    "33. Python simplifica la creación de API RESTful.",
    "34. Los equipos de desarrollo colaboran en proyectos de Python mediante control de versiones.",
    "35. Python mejora la capacidad de análisis en el ámbito de la economía.",
    "36. Los profesores de informática enseñarán algoritmos en Python.",
    "37. Python fomenta la creatividad en la resolución de problemas.",
    "38. Los desarrolladores optimizan el código Python para aumentar el rendimiento.",
    "39. Python ofrece herramientas para el aprendizaje automático.",
    "40. Los ingenieros de redes configuran y administran redes con scripts en Python.",
    "41. Python soporta la programación orientada a objetos y la programación funcional.",
    "42. Los ingenieros eléctricos diseñan sistemas embebidos utilizando Python.",
    "43. Python ayuda a los periodistas de datos a procesar grandes volúmenes de información.",
    "44. Los programadores diseñan sistemas de recomendación con Python.",
    "45. Python facilita la integración con tecnologías emergentes.",
    "46. Los desarrolladores utilizan Python para crear chatbots.",
    "47. Python permite a los científicos realizar simulaciones de física cuántica.",
    "48. Los expertos en marketing digital analizan el comportamiento de los usuarios con Python.",
    "49. Python se adapta fácilmente a proyectos de desarrollo ágil.",
    "50. Los programadores implementan algoritmos de búsqueda en Python.",
    "51. Python permite a los arquitectos de software construir soluciones escalables.",
    "52. Los expertos en inteligencia artificial entrenan modelos de aprendizaje profundo con Python.",
    "53. Python agiliza el procesamiento de señales en aplicaciones multimedia.",
    "54. Los ingenieros de software resuelven problemas de concurrencia con Python.",
    "55. Python facilita la creación de servidores de aplicaciones robustos.",
    "56. Los científicos modelan procesos químicos complejos con Python.",
    "57. Python apoya el desarrollo de software para dispositivos IoT.",
    "58. Los desarrolladores escriben aplicaciones de redes neuronales en Python.",
    "59. Python permite a los equipos de TI gestionar sistemas operativos.",
    "60. Los expertos en finanzas programan simulaciones económicas en Python.",
    "61. Python simplifica el acceso a API externas.",
    "62. Los arquitectos de software diseñan sistemas modulares con Python.",
    "63. Python ayuda a los ingenieros de sonido a procesar audio.",
    "64. Los desarrolladores diseñan interfaces de usuario modernas con Python.",
    "65. Python facilita la creación de sistemas de pago en línea.",
    "66. Los científicos sociales analizan datos demográficos con Python.",
    "67. Python permite a los desarrolladores gestionar grandes volúmenes de datos.",
    "68. Los programadores escriben pruebas automatizadas en Python.",
    "69. Python soporta la creación de servicios de mensajería en tiempo real.",
    "70. Los matemáticos calculan estadísticas avanzadas con Python.",
    "71. Python impulsa el desarrollo de tecnologías de reconocimiento facial.",
    "72. Los desarrolladores implementan modelos de predicción en Python.",
    "73. Python facilita la escritura de código multihilo.",
    "74. Los científicos computacionales modelan estructuras moleculares con Python.",
    "75. Python permite a los investigadores realizar análisis de texto.",
    "76. Los ingenieros aeroespaciales desarrollan simuladores de vuelo con Python.",
    "77. Python facilita la conexión con sistemas distribuidos.",
    "78. Los expertos en robótica programan autómatas en Python.",
    "79. Python soporta la creación de sistemas de gestión empresarial.",
    "80. Los analistas financieros automatizan cálculos bursátiles con Python.",
    "81. Python permite a los expertos en clima analizar patrones meteorológicos.",
    "82. Los ingenieros industriales optimizan procesos productivos con Python.",
    "83. Python impulsa el desarrollo de sistemas autónomos.",
    "84. Los programadores diseñan sistemas de control de versiones con Python.",
    "85. Python simplifica el manejo de grandes conjuntos de datos geoespaciales.",
    "86. Los desarrolladores implementan sistemas de criptografía en Python.",
    "87. Python facilita el desarrollo de aplicaciones de salud digital.",
    "88. Los expertos en ciberseguridad desarrollan herramientas de detección en Python.",
    "89. Python apoya la creación de sistemas de administración educativa.",
    "90. Los programadores diseñan plataformas de comercio electrónico con Python.",
    "91. Python permite a los ingenieros de software mejorar la escalabilidad de sus aplicaciones.",
    "92. Los desarrolladores construyen herramientas de análisis financiero en Python.",
    "93. Python apoya la creación de soluciones de almacenamiento en la nube.",
    "94. Los científicos ambientales modelan ecosistemas complejos con Python.",
    "95. Python acelera la implementación de tecnologías de visión por computadora.",
    "96. Los desarrolladores diseñan sistemas de monitoreo en tiempo real con Python.",
    "97. Python soporta el desarrollo de tecnologías de reconocimiento de voz.",
    "98. Los ingenieros de software escriben aplicaciones distribuidas en Python.",
    "99. Python facilita la creación de sistemas de procesamiento de imágenes.",
    "100. Los programadores mejoran la seguridad de las redes mediante herramientas desarrolladas en Python.",

]

oraciones_pasivas = [
    "1. Las aplicaciones eficientes son creadas por los desarrolladores en Python.",
    "2. Un código limpio y legible es facilitado por Python.",
    "3. Python es elegido por muchos programadores por su versatilidad.",
    "4. Las aplicaciones web son desarrolladas por las empresas utilizando Python.",
    "5. Una gran cantidad de bibliotecas útiles es ofrecida por Python.",
    "6. Python es aprendido rápidamente por los principiantes.",
    "7. Python es empleado por los científicos de datos en sus investigaciones.",
    "8. La creación de scripts automatizados es simplificada por Python.",
    "9. Los proyectos complejos son preferidos por los ingenieros de software con Python.",
    "10. El desarrollo de proyectos de inteligencia artificial es acelerado por Python.",
    "11. Python es aprendido por los estudiantes en sus cursos de informática.",
    "12. Los planos de estudio de las universidades incluyen Python.",
    "13. Los problemas matemáticos complejos son resueltos por los programadores con Python.",
    "14. Los prototipos rápidos son creados por los diseñadores de videojuegos utilizando Python.",
    "15. Las aplicaciones móviles están escritas por los desarrolladores con Python.",
    "16. El desarrollo de software en múltiples plataformas es soportado por Python.",
    "17. La interacción con bases de datos es facilitada por Python.",
    "18. Los proyectos desarrollados en Python son financiados por las empresas de tecnología.",
    "19. Las simulaciones son realizadas por los ingenieros con Python.",
    "20. El análisis de datos masivos es realizado por los investigadores que utilizan Python.",
    "21. Las herramientas de visualización de datos son compatibles con Python.",
    "22. Los servidores web son creados por los programadores con frameworks de Python.",
    "23. El rendimiento de aplicaciones de procesamiento de datos es mejorado por Python.",
    "24. Las herramientas de seguridad informática están implementadas por expertos en Python.",
    "25. Los servicios en la nube son integrados por los desarrolladores que utilizan Python.",
    "26. Las ecuaciones complejas son modeladas por los matemáticos con Python.",
    "27. El desarrollo de aplicaciones de interfaz gráfica de usuario es soportado por Python.",
    "28. Las tareas repetitivas son automatizadas por los programadores con Python.",
    "29. La creación de programas científicos es acelerada por Python.",
    "30. Los datos son limpiados y transformados por los ingenieros de datos con Python.",
    "31. Las consultas en grandes bases de datos son realizadas por los analistas de datos con Python.",
    "32. Las secuencias genéticas son analizadas por los investigadores en biotecnología con Python.",
    "33. La creación de API RESTful es simplificada por Python.",
    "34. Los proyectos de Python son colaborados por los equipos de desarrollo mediante control de versiones.",
    "35. La capacidad de análisis en economía es mejorada por Python.",
    "36. Los algoritmos son enseñados por los profesores de informática que utilizan Python.",
    "37. La creatividad en la resolución de problemas es fomentada por Python.",
    "38. El rendimiento del código Python está optimizado por los desarrolladores.",
    "39. Las herramientas para el aprendizaje automático son ofrecidas por Python.",
    "40. Las redes son configuradas y administradas por los ingenieros de redes con scripts en Python."
    "41. La programación orientada a objetos y la programación funcional son soportadas por Python.",
    "42. Los sistemas embebidos son diseñados por los ingenieros eléctricos que utilizan Python.",
    "43. Los grandes volúmenes de información son procesados ​​por los periodistas de datos con Python.",
    "44. Los sistemas de recomendación están diseñados por los programadores con Python.",
    "45. Las tecnologías emergentes están integradas fácilmente por Python.",
    "46. Los chatbots son creados por los desarrolladores que utilizan Python.",
    "47. Las simulaciones de física cuántica son realizadas por los científicos con Python.",
    "48. El comportamiento de los usuarios es analizado por los expertos en marketing digital con Python.",
    "49. Los proyectos de desarrollo ágil son adaptados fácilmente por Python.",
    "50. Los algoritmos de búsqueda son implementados por los programadores en Python.",
    "51. Las soluciones escalables son construidas por los arquitectos de software con Python.",
    "52. Los modelos de aprendizaje profundo son entrenados por los expertos en inteligencia artificial con Python.",
    "53. El procesamiento de señales en aplicaciones multimedia está agilizado por Python.",
    "54. Los problemas de concurrencia son resueltos por los ingenieros de software con Python.",
    "55. Los servidores de aplicaciones robustos son creados por Python.",
    "56. Los procesos químicos complejos son modelados por los científicos con Python.",
    "57. El desarrollo de software para dispositivos IoT está apoyado por Python.",
    "58. Las aplicaciones de redes neuronales están escritas por los desarrolladores en Python.",
    "59. Los sistemas operativos son gestionados por los equipos de TI utilizando Python.",
    "60. Las simulaciones económicas son programadas por los expertos en finanzas con Python.",
    "61. El acceso a API externas está simplificado por Python.",
    "62. Los sistemas modulares están diseñados por los arquitectos de software con Python.",
    "63. El procesamiento de audio es realizado por los ingenieros de sonido con Python.",
    "64. Las interfaces de usuario modernas son diseñadas por los desarrolladores con Python.",
    "65. Los sistemas de pago en línea son creados por Python.",
    "66. Los datos demográficos son analizados por los científicos sociales con Python.",
    "67. Los grandes volúmenes de datos son gestionados por los desarrolladores que utilizan Python.",
    "68. Las pruebas automatizadas son escritas por los programadores en Python.",
    "69. Los servicios de mensajería en tiempo real son soportados por Python.",
    "70. Las estadísticas avanzadas son calculadas por los matemáticos con Python.",
    "71. Las tecnologías de reconocimiento facial son impulsadas por Python.",
    "72. Los modelos de predicción son implementados por los desarrolladores en Python.",
    "73. El código multihilo está escrito por los programadores en Python.",
    "74. Las estructuras moleculares son modeladas por los científicos computacionales con Python."
    "75. El análisis de texto es realizado por los investigadores con Python.",
    "76. Los simuladores de vuelo son desarrollados por los ingenieros aeroespaciales con Python.",
    "77. La conexión con sistemas distribuidos es facilitada por Python.",
    "78. Los autómatas son programados por los expertos en robótica con Python.",
    "79. Los sistemas de gestión empresarial son soportados por Python.",
    "80. Los cálculos bursátiles son automatizados por los analistas financieros con Python.",
    "81. Los patrones meteorológicos son analizados por los expertos en clima con Python.",
    "82. Los procesos productivos son optimizados por los ingenieros industriales con Python.",
    "83. Los sistemas autónomos son impulsados ​​por Python.",
    "84. Los sistemas de control de versiones son diseñados por los programadores con Python.",
    "85. Los conjuntos de datos geoespaciales son manejados por los desarrolladores con Python.",
    "86. Los sistemas de criptografía son implementados por los desarrolladores con Python.",
    "87. Las aplicaciones de salud digital son desarrolladas por Python.",
    "88. Las herramientas de detección de ciberseguridad son desarrolladas por expertos en Python.",
    "89. Los sistemas de administración educativa están respaldados por Python.",
    "90. Las plataformas de comercio electrónico están diseñadas por los programadores con Python.",
    "91. La escalabilidad de las aplicaciones es mejorada por los ingenieros de software con Python.",
    "92. Las herramientas de análisis financiero están construidas por los desarrolladores en Python.",
    "93. Las soluciones de almacenamiento en la nube son apoyadas por Python.",
    "94. Los ecosistemas complejos son modelados por los científicos ambientales con Python.",
    "95. Las tecnologías de visión por computadora se implementan rápidamente por Python.",
    "96. Los sistemas de monitoreo en tiempo real son diseñados por los desarrolladores con Python.",
    "97. Las tecnologías de reconocimiento de voz son soportadas por Python.",
    "98. Las aplicaciones distribuidas son escritas por los ingenieros de software en Python.",
    "99. Los sistemas de procesamiento de imágenes son creados por Python.",
    "100. Las herramientas de seguridad de redes son mejoradas por los programadores mediante Python."  
]

traducciones_activas = [
    "1. Developers create efficient applications i Python.",
    "2. Python facilitates clean and readable code.",
    "3. Many programmers choose Python for its versatility.",
    "4. Companies develop web applications using Python.",
    "5. Python offers a wide range of useful libraries.",
    "6. Beginners learn Python quickly.",
    "7. Data scientists use Python in their research.",
    "8. Python simplifies the creation of automated scripts.",
    "9. Software engineers prefer Python for complex projects.",
    "10. Python accelerates the development of artificial intelligence projects.",
    "11. Students learn Python in their computer science courses.",
    "12. Universities include Python in their curricula.",
    "13. Programmers solve complex mathematical problems with Python.",
    "14. Game designers create rapid prototypes using Python.",
    "15. Developers write mobile applications with Python.",
    "16. Python supports cross-platform software development.",
    "17. Python facilitates database interaction.",
    "18. Technology companies fund Python-based projects.",
    "19. Engineers conduct simulations using Python.",
    "20. Researchers perform big data analysis using Python. ",
    "21. Data visualization tools are compatible with Python.",
    "22. Programmers create web servers with Python frameworks.",
    "23. Python improves the performance of data processing applications.",
    "24. Security experts implement tools using Python. ",
    "25. Developers integrate cloud services with Python.",
    "26. Mathematicians model complex equations with Python.",
    "27. Python supports graphical user interface (GUI) application development.",
    "28. Programmers automate repetitive tasks with Python.",
    "29. Python accelerates the creation of scientific programs.",
    "30. Data engineers clean and transform data with Python.",
    "31. Data analysts run queries on large databases using Python.",
    "32. Biotech researchers analyze genetic sequences with Python.",
    "33. Python simplifies the creation of RESTful APIs.",
    "34. Development teams collaborate on Python projects through version control.",
    "35. Python enhances analysis capabilities in economics.",
    "36. Computer science teachers teach algorithms using Python.",
    "37. Python fosters creativity in problem-solving.",
    "38. Developers optimize Python code performance.",
    "39. Python provides tools for machine learning.",
    "40. Network engineers configure and manage networks with Python scripts.",
    "41. Python supports object-oriented and functional programming.",
    "42. Electrical engineers design embedded systems using Python.",
    "43. Data journalists process large volumes of information with Python.",
    "44. Programmers design recommendation systems with Python.",
    "45. Emerging technologies are easily integrated with Python.",
    "46. Developers create chatbots using Python.",
    "47. Scientists run quantum physics simulations with Python.",
    "48. Digital marketing experts analyze user behavior with Python.",
    "49. Python adapts easily to agile development projects.",
    "50. Programmers implement search algorithms in Python.",
    "51. Software architects build scalable solutions with Python.",
    "52. AI experts train deep learning models with Python.",
    "53. Python accelerates signal processing in multimedia applications.",
    "54. Software engineers solve concurrency problems with Python.",
    "55. Python creates robust application servers.",
    "56. Scientists model complex chemical processes with Python.",
    "57. Python supports software development for IoT devices.",
    "58. Developers write neural network applications with Python.",
    "59. IT teams manage operating systems using Python.",
    "60. Financial experts program economic simulations with Python.",
    "61. Python simplifies access to external APIs.",
    "62. Software architects design modular systems with Python.",
    "63. Audio engineers process sound with Python.",
    "64. Developers design modern user interfaces with Python.",
    "65. Python creates online payment systems.",
    "66. Social scientists analyze demographic data with Python.",
    "67. Developers manage large volumes of data with Python.",
    "68. Programmers write automated tests in Python.",
    "69. Python supports real-time messaging services.",
    "70. Mathematicians calculate advanced statistics with Python.",
    "71. Python powers facial recognition technologies.",
    "72. Developers implement prediction models in Python.",
    "73. Programmers write multithreaded code in Python.",
    "74. Computational scientists model molecular structures with Python.",
    "75. Researchers perform text analysis with Python.",
    "76. Aerospace engineers develop flight simulators with Python.",
    "77. Python facilitates connection with distributed systems.",
    "78. Robotics experts program automatons with Python.",
    "79. Python supports enterprise management systems.",
    "80. Financial analysts automate stock market calculations with Python.",
    "81. Climate experts analyze weather patterns with Python.",
    "82. Industrial engineers optimize production processes with Python.",
    "83. Python powers autonomous systems.",
    "84. Programmers design version control systems with Python.",
    "85. Developers handle geospatial datasets with Python.",
    "86. Python implements cryptography systems.",
    "87. Python develops digital health applications.",
    "88. Experts build cybersecurity detection tools with Python.",
    "89. Python supports educational management systems.",
    "90. Programmers design e-commerce platforms with Python.",
    "91. Software engineers improve application scalability with Python.",
    "92. Developers build financial analysis tools in Python.",
    "93. Python supports cloud storage solutions.",
    "94. Environmental scientists model complex ecosystems with Python.",
    "95. Python implements computer vision technologies quickly.",
    "96. Developers design real-time monitoring systems with Python.",
    "97. Python supports voice recognition technologies.",
    "98. Software engineers write distributed applications in Python.",
    "99. Python creates image processing systems.",
    "100. Programmers improve network security tools with Python.",
]

traducciones_pasivas = [
    "1. Efficient applications are created by developers in Python.",
    "2. Clean and readable code is facilitated by Python.",
    "3. Python is chosen by many programmers for its versatility.",
    "4. Web applications are developed by companies using Python.",
    "5. A wide range of useful libraries is offered by Python.",
    "6. Python is quickly learned by beginners.",
    "7. Python is used by data scientists in their research.",
    "8. The creation of automated scripts is simplified by Python.",
    "9. Complex projects are preferred by software engineers with Python.",
    "10. The development of artificial intelligence projects is accelerated by Python.",
    "11. Python is learned by students in their computer science courses.",
    "12. Python is included by universities in their curricula.",
    "13. Complex mathematical problems are solved by programmers with Python.",
    "14. Rapid prototypes are created by game designers using Python.",
    "15. Mobile applications are written by developers with Python.",
    "16. Cross-platform software development is supported by Python. ",
    "17. Database interaction is facilitated by Python.",
    "18. Python-based projects are funded by technology companies. ",
    "19. Simulations are conducted by engineers using Python.",
    "20. Big data analysis is performed by researchers using Python.",
    "21. Data visualization tools are made compatible with Python.",
    "22. Web servers are created by programmers with Python frameworks.",
    "23. The performance of data processing applications is improved by Python.",
    "24. Security tools are implemented by experts with Python.",
    "25. Cloud services are integrated by developers using Python.",
    "26. Complex equations are modeled by mathematicians with Python.",
    "27. GUI application development is supported by Python.",
    "28. Repetitive tasks are automated by programmers with Python.",
    "29. Scientific programs are created faster with Python.",
    "30. Data is cleaned and transformed by data engineers with Python.",
    "31. Large database queries are run by data analysts with Python.",
    "32. Genetic sequences are analyzed by biotech researchers with Python.",
    "33. RESTful APIs are simplified by Python.",
    "34. Python projects are collaborated on by development teams through version control.",
    "35. Analysis capabilities in economics are enhanced by Python.",
    "36. Algorithms are taught by computer science teachers using Python.",
    "37. Creativity in problem-solving is fostered by Python.",
    "38. Python code performance is optimized by developers.",
    "39. Machine learning tools are provided by Python.",
    "40. Networks are configured and managed by network engineers with Python scripts.",
    "41. Object-oriented and functional programming are supported by Python.",
    "42. Embedded systems are designed by electrical engineers using Python.",
    "43. Large volumes of information are processed by data journalists with Python.",
    "44. Recommendation systems are designed by programmers with Python.",
    "45. Emerging technologies are easily integrated with Python.",
    "46. Chatbots are created by developers using Python.",
    "47. Quantum physics simulations are run by scientists with Python.",
    "48. User behavior is analyzed by digital marketing experts with Python.",
    "49. Agile development projects are easily adapted by Python.",
    "50. Search algorithms are implemented by programmers in Python.",
    "51. Scalable solutions are built by software architects with Python.",
    "52. Deep learning models are trained by AI experts with Python.",
    "53. Signal processing in multimedia applications is accelerated by Python.",
    "54. Concurrency problems are solved by software engineers with Python.",
    "55. Robust application servers are created by Python.",
    "56. Complex chemical processes are modeled by scientists with Python.",
    "57. Software development for IoT devices is supported by Python.",
    "58. Neural network applications are written by developers with Python. ",
    "59. Operating systems are managed by IT teams using Python.",
    "60. Economic simulations are programmed by financial experts with Python.",
    "61. Access to external APIs is simplified by Python.",
    "62. Modular systems are designed by software architects with Python.",
    "63. Sound processing is done by audio engineers with Python.",
    "64. Modern user interfaces are designed by developers with Python.",
    "65. Online payment systems are created by Python.",
    "66. Demographic data is analyzed by social scientists with Python.",
    "67. Large volumes of data are managed by developers using Python.",
    "68. Automated tests are written by programmers in Python.",
    "69. Real-time messaging services are supported by Python.",
    "70. Advanced statistics are calculated by mathematicians with Python.",
    "71. Facial recognition technologies are powered by Python.",
    "72. Prediction models are implemented by developers in Python.",
    "73. Multithreaded code is written by programmers in Python.",
    "74. Molecular structures are modeled by computational scientists with Python.",
    "75. Text analysis is performed by researchers with Python.",
    "76. Flight simulators are developed by aerospace engineers with Python.",
    "77. Connection with distributed systems is facilitated by Python.",
    "78. Automatons are programmed by robotics experts with Python.",
    "79. Enterprise management systems are supported by Python.",
    "80. Stock market calculations are automated by financial analysts with Python.",
    "81. Weather patterns are analyzed by climate experts with Python.",
    "82. Production processes are optimized by industrial engineers with Python.",
    "83. Autonomous systems are powered by Python.",
    "84. Version control systems are designed by programmers with Python.",
    "85. Geospatial datasets are handled by developers with Python.",
    "86. Cryptography systems are implemented by developers with Python.",
    "87. Digital health applications are developed by Python.",
    "88. Cybersecurity detection tools are developed by experts with Python.",
    "89. Educational management systems are supported by Python.",
    "90. E-commerce platforms are designed by programmers with Python.",
    "91. Application scalability is improved by software engineers with Python.",
    "92. Financial analysis tools are built by developers in Python.",
    "93. Cloud storage solutions are supported by Python.",
    "94. Complex ecosystems are modeled by environmental scientists with Python.",
    "95. Computer vision technologies are quickly implemented by Python.",
    "96. Real-time monitoring systems are designed by developers with Python.",
    "97. Voice recognition technologies are supported by Python.",
    "98. Distributed applications are written by software engineers in Python.",
    "99. Image processing systems are created by Python.",
    "100. Network security tools are improved by programmers with Python.", 
]

# Función para practicar oraciones activas -> pasivas y traducir al inglés
def activas_a_pasivas():
    for i in range(len(oraciones_activas)):
        print(f"Oración activa #{i+1}: {oraciones_activas[i]}")
        respuesta_pasiva = input("Ahora, escribe la forma pasiva de esta oración: ").strip()
        
        if respuesta_pasiva == oraciones_pasivas[i]:
            print("¡Correcto en voz pasiva!")
        else:
            print(f"Incorrecto. La oración pasiva correcta es: {oraciones_pasivas[i]}")

        respuesta_traduccion = input("Traduce la oración activa al inglés: ").strip()
        
        if respuesta_traduccion == traducciones_activas[i]:
            print("¡Correcto en la traducción al inglés!")
        else:
            print(f"Incorrecto. La traducción correcta es: {traducciones_activas[i]}")
        print()

# Función para practicar oraciones pasivas -> activas y traducir al inglés
def pasivas_a_activas():
    for i in range(len(oraciones_pasivas)):
        print(f"Oración pasiva #{i+1}: {oraciones_pasivas[i]}")
        respuesta_activa = input("Ahora, escribe la forma activa de esta oración: ").strip()
        
        if respuesta_activa == oraciones_activas[i]:
            print("¡Correcto en voz activa!")
        else:
            print(f"Incorrecto. La oración activa correcta es: {oraciones_activas[i]}")

        respuesta_traduccion = input("Traduce la oración pasiva al inglés: ").strip()

        if respuesta_traduccion == traducciones_pasivas[i]:
            print("¡Correcto en la traducción al inglés!")
        else:
            print(f"Incorrecto. La traducción correcta es: {traducciones_pasivas[i]}")
        print()

# Función para mostrar el menú y seleccionar opción
def menu():
    while True:
        print("Practica oraciones en voz activa y pasiva, y su traducción al inglés.")
        print("1. Convertir oraciones activas a pasivas y traducir al inglés")
        print("2. Convertir oraciones pasivas a activas y traducir al inglés")
        print("3. Salir")
        
        opcion = input("Por favor, elige una opción (1-3): ")
        
        if opcion == "1":
            activas_a_pasivas()
        elif opcion == "2":
            pasivas_a_activas()
        elif opcion == "3":
            print("Saliendo del programa.")
            break
        else:
            print("Opción no válida. Por favor, elige de nuevo.")
        print()

# Ejecuta el programa
if __name__ == "__main__":
    menu()
