def verificar_entrada(correcta, idioma):
    while True:
        entrada = input(f"Escribe ortográficamente la siguiente oración en {idioma}: \n{correcta}\nTu respuesta: ")
        if entrada.strip() == correcta:
            print("¡Correcto!")
            break
        else:
            print("Incorrecto. Inténtalo de nuevo.")

# Lista de oraciones en varios idiomas
oraciones = {
    'ingles': [
        "Python is a versatile programming language.",
        "Lists are mutable in Python.",
        "Dictionaries store key-value pairs.",
        "Tuples are immutable data structures.",
        "Conditional statements control program flow.",
        "Loops repeat code until a condition is met.",
        "Functions encapsulate reusable code blocks.",
        "Classes define object blueprints.",
        "Modules help organize Python code.",
        "Exception handling manages errors gracefully.",
        "File handling allows reading and writing files.",
        "Regular expressions match patterns in text.",
        "Lambda functions create anonymous functions.",
        "List comprehensions provide concise ways to create lists.",
        "Generators produce values one at a time.",
        "Decorators modify the behavior of functions or methods.",
        "Recursion involves functions calling themselves.",
        "Virtual environments isolate Python environments.",
        "Concurrency allows for multitasking in Python.",
        "Assertions verify conditions in code.",
        "Unit tests validate individual units of code.",
        "Integration tests verify interactions between units.",
        "End-to-end tests simulate real user scenarios.",
        "Version control manages changes to code over time.",
        "GitHub is a popular platform for hosting Git repositories.",
        "APIs enable communication between software applications.",
        "JSON is a lightweight data interchange format.",
        "RESTful APIs follow principles of Representational State Transfer.",
        "Web scraping extracts data from websites.",
        "Machine learning models make predictions based on data.",
        "Data visualization presents data in graphical formats.",
        "Big O notation analyzes algorithms for efficiency.",
        "Object-oriented programming emphasizes objects and classes.",
        "Functional programming focuses on functions as fundamental units.",
        "Microservices architecture decomposes applications into smaller services.",
        "Blockchain technology secures digital transactions."
    ],
    'espanol': [
        "Python es un lenguaje de programación versátil.",
        "Las listas son mutables en Python.",
        "Los diccionarios almacenan pares clave-valor.",
        "Las tuplas son estructuras de datos inmutables.",
        "Las declaraciones condicionales controlan el flujo del programa.",
        "Los bucles repiten código hasta que se cumple una condición.",
        "Las funciones encapsulan bloques de código reutilizables.",
        "Las clases definen los planos de los objetos.",
        "Los módulos ayudan a organizar el código de Python.",
        "El manejo de excepciones gestiona errores de manera elegante.",
        "El manejo de archivos permite leer y escribir archivos.",
        "Las expresiones regulares coinciden con patrones en el texto.",
        "Las funciones lambda crean funciones anónimas.",
        "Las comprensiones de lista proporcionan formas concisas de crear listas.",
        "Los generadores producen valores uno a uno.",
        "Los decoradores modifican el comportamiento de funciones o métodos.",
        "La recursión implica que las funciones se llamen a sí mismas.",
        "Los entornos virtuales aislan los entornos de Python.",
        "La concurrencia permite la multitarea en Python.",
        "Las aserciones verifican condiciones en el código.",
        "Las pruebas unitarias validan unidades individuales de código.",
        "Las pruebas de integración verifican interacciones entre unidades.",
        "Las pruebas end-to-end simulan escenarios reales de usuarios.",
        "El control de versiones gestiona los cambios en el código a lo largo del tiempo.",
        "GitHub es una plataforma popular para alojar repositorios de Git.",
        "Las APIs permiten la comunicación entre aplicaciones de software.",
        "JSON es un formato ligero de intercambio de datos.",
        "Las APIs RESTful siguen los principios de Transferencia de Estado Representacional.",
        "La extracción de datos web extrae datos de sitios web.",
        "Los modelos de aprendizaje automático hacen predicciones basadas en datos.",
        "La visualización de datos presenta datos en formatos gráficos.",
        "La notación Big O analiza algoritmos para la eficiencia.",
        "La programación orientada a objetos enfatiza objetos y clases.",
        "La programación funcional se centra en las funciones como unidades fundamentales.",
        "La arquitectura de microservicios descompone las aplicaciones en servicios más pequeños.",
        "La tecnología blockchain asegura transacciones digitales."
    ],
    'frances': [
        "Python est un langage de programmation polyvalent.",
        "Les listes sont modifiables en Python.",
        "Les dictionnaires stockent des paires clé-valeur.",
        "Les tuples sont des structures de données immuables.",
        "Les instructions conditionnelles contrôlent le flux du programme.",
        "Les boucles répètent le code jusqu'à ce qu'une condition soit remplie.",
        "Les fonctions encapsulent des blocs de code réutilisables.",
        "Les classes définissent les plans des objets.",
        "Les modules aident à organiser le code Python.",
        "La gestion des exceptions gère les erreurs de manière élégante.",
        "La gestion des fichiers permet de lire et d'écrire des fichiers.",
        "Les expressions régulières correspondent à des motifs dans le texte.",
        "Les fonctions lambda créent des fonctions anonymes.",
        "Les compréhensions de liste fournissent des moyens concis de créer des listes.",
        "Les générateurs produisent des valeurs une par une.",
        "Les décorateurs modifient le comportement des fonctions ou méthodes.",
        "La récursivité implique que les fonctions s'appellent elles-mêmes.",
        "Les environnements virtuels isolent les environnements de Python.",
        "La concurrence permet le multitâche en Python.",
        "Les assertions vérifient les conditions dans le code.",
        "Les tests unitaires valident les unités individuelles de code.",
        "Les tests d'intégration vérifient les interactions entre unités.",
        "Les tests end-to-end simulent des scénarios réels d'utilisateurs.",
        "Le contrôle de version gère les modifications du code au fil du temps.",
        "GitHub est une plateforme populaire pour héberger des dépôts Git.",
        "Les APIs permettent la communication entre les applications logicielles.",
        "JSON est un format léger d'échange de données.",
        "Les APIs RESTful suivent les principes de Transfer State Representationnel.",
        "Le web scraping extrait des données des sites web.",
        "Les modèles d'apprentissage automatique font des prédictions basées sur des données.",
        "La visualisation de données présente des données sous forme graphique.",
        "La notation Big O analyse les algorithmes pour l'efficacité.",
        "La programmation orientée objet met l'accent sur les objets et les classes.",
        "La programmation fonctionnelle se concentre sur les fonctions comme unités fondamentales.",
        "L'architecture de microservices décompose les applications en services plus petits.",
        "La technologie blockchain sécurise les transactions numériques."
    ],
    'aleman': [
        "Python ist eine vielseitige Programmiersprache.",
        "Listen sind in Python veränderbar.",
        "Wörterbücher speichern Schlüssel-Wert-Paare.",
        "Tupel sind unveränderliche Datenstrukturen.",
        "Bedingte Anweisungen steuern den Programmfluss.",
        "Schleifen wiederholen den Code, bis eine Bedingung erfüllt ist.",
        "Funktionen umschließen wiederverwendbare Codeblöcke.",
        "Klassen definieren Objektbaupläne.",
        "Module helfen beim Organisieren von Python-Code.",
        "Die Fehlerbehandlung verwaltet Fehler elegant.",
        "Die Dateiverarbeitung ermöglicht das Lesen und Schreiben von Dateien.",
        "Reguläre Ausdrücke entsprechen Mustern im Text.",
        "Lambda-Funktionen erstellen anonyme Funktionen.",
        "List Comprehensions bieten prägnante Möglichkeiten zum Erstellen von Listen.",
        "Generatoren erzeugen Werte nacheinander.",
        "Dekorateure ändern das Verhalten von Funktionen oder Methoden.",
        "Rekursion bedeutet, dass Funktionen sich selbst aufrufen.",
        "Virtuelle Umgebungen isolieren Python-Umgebungen.",
        "Die Nebenläufigkeit ermöglicht Multitasking in Python.",
        "Assertions überprüfen Bedingungen im Code.",
        "Unit Tests validieren einzelne Codeeinheiten.",
        "Integrationstests überprüfen Interaktionen zwischen Einheiten.",
        "End-to-end-Tests simulieren reale Benutzerszenarien.",
       
