def verificar_entrada(correcta, idioma):
    while True:
        entrada = input(f"Escribe ortográficamente la siguiente oración en {idioma}: \n{correcta}\nTu respuesta: ")
        if entrada.strip() == correcta:
            print("¡Correcto!")
            break
        else:
            print("Incorrecto. Inténtalo de nuevo.")

# Lista de oraciones en varios idiomas
oraciones = {
    'latin': [
        "Carpe diem quam minimum credula postero.",
        "Alea iacta est.",
        "Veni, vidi, vici.",
        "Tempus fugit.",
        "Memento mori.",
        "Amor vincit omnia.",
        "Cogito, ergo sum.",
        "Ad astra per aspera.",
        "Ave Caesar, morituri te salutant.",
        "Per aspera ad astra.",
        "Dulce et decorum est pro patria mori.",
        "Sic parvis magna.",
        "Non ducor, duco.",
        "Audentes fortuna iuvat.",
        "O tempora, o mores!",
        "Festina lente.",
        "Acta non verba.",
        "Astra inclinant, sed non obligant.",
        "Per ardua ad astra.",
        "Carpe noctem.",
        "Cura ut valeas!",
        "Noli turbare circulos meos.",
        "Sic itur ad astra.",
        "Lux in tenebris lucet.",
        "Per angusta ad augusta.",
        "Fortuna audaces iuvat.",
        "Aut viam inveniam aut faciam.",
        "Vivere est cogitare.",
        "Virtus in medio stat.",
        "Luctor et emergo.",
        "Si vis pacem, para bellum."
    ],
    'ingles': [
        "Carpe diem, seize the day.",
        "The die is cast.",
        "I came, I saw, I conquered.",
        "Time flies.",
        "Remember you will die.",
        "Love conquers all.",
        "I think, therefore I am.",
        "To the stars through difficulties.",
        "Hail Caesar, those who are about to die salute you.",
        "Through hardships to the stars.",
        "It is sweet and fitting to die for one's country.",
        "Greatness from small beginnings.",
        "I am not led, I lead.",
        "Fortune favors the bold.",
        "Oh the times, oh the customs!",
        "Make haste slowly.",
        "Deeds, not words.",
        "The stars incline us, they do not bind us.",
        "Through adversity to the stars.",
        "Seize the night.",
        "Take care of yourself!",
        "Do not disturb my circles.",
        "Thus you shall go to the stars.",
        "The light shines in the darkness.",
        "Through difficulties to honors.",
        "Fortune favors the bold.",
        "Either I will find a way or I will make one.",
        "To live is to think.",
        "Virtue stands in the middle.",
        "I struggle and emerge.",
        "If you want peace, prepare for war."
    ],
    'espanol': [
        "Aprovecha el día, confía lo menos posible en el mañana.",
        "La suerte está echada.",
        "Vine, vi, vencí.",
        "El tiempo vuela.",
        "Recuerda que morirás.",
        "El amor todo lo vence.",
        "Pienso, luego existo.",
        "Hacia las estrellas a través de las dificultades.",
        "Salve César, los que van a morir te saludan.",
        "A través de las dificultades hacia las estrellas.",
        "Es dulce y honorable morir por la patria.",
        "La grandeza surge de pequeños comienzos.",
        "No soy llevado, yo conduzco.",
        "La fortuna favorece a los valientes.",
        "¡Oh tiempos, oh costumbres!",
        "Date prisa despacio.",
        "Hechos, no palabras.",
        "Las estrellas nos inclinan, pero no nos obligan.",
        "A través de la adversidad hacia las estrellas.",
        "Aprovecha la noche.",
        "¡Cuídate!",
        "No perturbes mis círculos.",
        "Así irás hacia las estrellas.",
        "La luz brilla en la oscuridad.",
        "A través de las dificultades hacia los honores.",
        "La fortuna favorece a los audaces.",
        "O encuentro un camino o lo hago.",
        "Vivir es pensar.",
        "La virtud está en el medio.",
        "Luchando, y emergo.",
        "Si quieres la paz, prepara la guerra."
    ],
    'griego': [
        "Ἅπαντα χωρεῖ καὶ οὐδὲν μένει.",
        "Ἡ τύχη τοὺς τολμῶντας βοηθεῖ.",
        "Ἐπὶ τοὺς πόνους τοὺς καιρίους ἀναγκάζεται.",
        "Ἕν οἶδα ὅτι οὐδὲν οἶδα.",
        "Μέγας ὁ Θεός.",
        "Εἰ δὲ μή τι ποιεῖς, τί ἀποδείξεις;",
        "Κατά βάθους γιγνώσκω, οὐκ εἰδώς.",
        "Γνῶθι σεαυτόν.",
        "Εὐδαίμων ὁ νικῶν ἐαυτόν.",
        "Ὁ βίος βραχύς, ἡ δὲ τέχνη μακρή.",
        "Ἵλεως ὁ Θεός.",
        "Γῆν ἑρπετὰ καὶ πετεινὰ καὶ ἑρπετὰ καὶ ἰχθύες.",
        "Πολλὰ τὰ δεινὰ κοὐδὲν ἀνθρώπου δεινότερον πέλει.",
        "Πλὴν ἐπεὶ πάντες ἀποθνῄσκομεν, δῶρα τοις δεῖ πέμπειν θεοῖς.",
        "Ἀεὶ κολοιὸς παρὰ κολοιῷ ἱζάνει.",
        "Κρᾶτα γὰρ ἀνάγκῃ.",
        "Τὰ γὰρ πρόσφορα μακάρια.",
        "Πρὸς γὰρ καὶ καλὰ τὸ κακὸν μικρὸν.",
        "Τὸν τοῦ νοῦν ἀστὴρ φαίνει.",
        "Εὖ πάσχοντες ἀγαθοὶ καὶ πλούσιοι φαίνεσθε.",
        "Εὖ πάσχοντες ἀγαθοὶ καὶ πλούσιοι φαίνεσθε.",
        "Ἡ σοφία πρώτη χρεία τῷ ἀνθρώπῳ.",
        "Ἐν οἴνῳ ἀλήθεια.",
        "Οὔτος ἐγώ.",
        "Δικαίας γὰρ ἀρχὰς βίος."
    ]
