import random

def cargar_ejercicios_pluscuamperfecto():
    """
    Carga los 100 ejercicios predefinidos de conjugación verbal (pluscuamperfecto)
    directamente en el código.
    """
    print("Cargando 100 ejercicios de Conjugación Verbal (Pluscuamperfecto) directamente...")
    return {
        "Morfología": {
            "Intermedio": {
                "Conjugación verbal (Pluscuamperfecto)": [
                    {"pregunta": "Conjuga el verbo 'hablar' en pluscuamperfecto de indicativo, primera persona singular (yo).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había hablado", "explicacion": "Yo había hablado."},
                    {"pregunta": "Conjuga el verbo 'comer' en pluscuamperfecto de indicativo, segunda persona singular (tú).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "habías comido", "explicacion": "Tú habías comido."},
                    {"pregunta": "Conjuga el verbo 'vivir' en pluscuamperfecto de indicativo, tercera persona singular (él/ella/usted).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había vivido", "explicacion": "Él/Ella/Usted había vivido."},
                    {"pregunta": "Conjuga el verbo 'escribir' en pluscuamperfecto de indicativo, primera persona plural (nosotros/as).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "habíamos escrito", "explicacion": "Nosotros/as habíamos escrito."},
                    {"pregunta": "Conjuga el verbo 'leer' en pluscuamperfecto de indicativo, segunda persona plural (vosotros/as).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "habíais leído", "explicacion": "Vosotros/as habíais leído."},
                    {"pregunta": "Conjuga el verbo 'salir' en pluscuamperfecto de indicativo, tercera persona plural (ellos/ellas/ustedes).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "habían salido", "explicacion": "Ellos/Ellas/Ustedes habían salido."},
                    {"pregunta": "Conjuga el verbo 'ir' en pluscuamperfecto de indicativo, primera persona singular (yo).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había ido", "explicacion": "Yo había ido."},
                    {"pregunta": "Conjuga el verbo 'hacer' en pluscuamperfecto de indicativo, tercera persona singular (él/ella/usted).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había hecho", "explicacion": "Él/Ella/Usted había hecho."},
                    {"pregunta": "Conjuga el verbo 'ver' en pluscuamperfecto de indicativo, primera persona singular (yo).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había visto", "explicacion": "Yo había visto."},
                    {"pregunta": "Conjuga el verbo 'cantar' en pluscuamperfecto de indicativo, primera persona plural (nosotros/as).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "habíamos cantado", "explicacion": "Nosotros/as habíamos cantado."},
                    {"pregunta": "Conjuga el verbo 'poder' en pluscuamperfecto de indicativo, tercera persona plural (ellos/ellas/ustedes).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "habían podido", "explicacion": "Ellos/Ellas/Ustedes habían podido."},
                    {"pregunta": "Conjuga el verbo 'saber' en pluscuamperfecto de indicativo, primera persona singular (yo).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había sabido", "explicacion": "Yo había sabido."},
                    {"pregunta": "Conjuga el verbo 'decir' en pluscuamperfecto de indicativo, segunda persona singular (tú).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "habías dicho", "explicacion": "Tú habías dicho."},
                    {"pregunta": "Conjuga el verbo 'venir' en pluscuamperfecto de indicativo, tercera persona plural (ellos/ellas/ustedes).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "habían venido", "explicacion": "Ellos/Ellas/Ustedes habían venido."},
                    {"pregunta": "Conjuga el verbo 'tener' en pluscuamperfecto de indicativo, primera persona singular (yo).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había tenido", "explicacion": "Yo había tenido."},
                    {"pregunta": "Conjuga el verbo 'poner' en pluscuamperfecto de indicativo, segunda persona singular (tú).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "habías puesto", "explicacion": "Tú habías puesto."},
                    {"pregunta": "Conjuga el verbo 'abrir' en pluscuamperfecto de indicativo, tercera persona singular (él/ella/usted).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había abierto", "explicacion": "Él/Ella/Usted había abierto."},
                    {"pregunta": "Conjuga el verbo 'romper' en pluscuamperfecto de indicativo, primera persona plural (nosotros/as).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "habíamos roto", "explicacion": "Nosotros/as habíamos roto."},
                    {"pregunta": "Conjuga el verbo 'volver' en pluscuamperfecto de indicativo, segunda persona plural (vosotros/as).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "habíais vuelto", "explicacion": "Vosotros/as habíais vuelto."},
                    {"pregunta": "Conjuga el verbo 'cubrir' en pluscuamperfecto de indicativo, tercera persona plural (ellos/ellas/ustedes).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "habían cubierto", "explicacion": "Ellos/Ellas/Ustedes habían cubierto."},
                    {"pregunta": "Conjuga el verbo 'dormir' en pluscuamperfecto de indicativo, primera persona singular (yo).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había dormido", "explicacion": "Yo había dormido."},
                    {"pregunta": "Conjuga el verbo 'sentir' en pluscuamperfecto de indicativo, segunda persona singular (tú).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "habías sentido", "explicacion": "Tú habías sentido."},
                    {"pregunta": "Conjuga el verbo 'pedir' en pluscuamperfecto de indicativo, tercera persona singular (él/ella/usted).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había pedido", "explicacion": "Él/Ella/Usted había pedido."},
                    {"pregunta": "Conjuga el verbo 'morir' en pluscuamperfecto de indicativo, primera persona plural (nosotros/as).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "habíamos muerto", "explicacion": "Nosotros/as habíamos muerto."},
                    {"pregunta": "Conjuga el verbo 'preferir' en pluscuamperfecto de indicativo, segunda persona plural (vosotros/as).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "habíais preferido", "explicacion": "Vosotros/as habíais preferido."},
                    {"pregunta": "Conjuga el verbo 'reír' en pluscuamperfecto de indicativo, tercera persona plural (ellos/ellas/ustedes).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "habían reído", "explicacion": "Ellos/Ellas/Ustedes habían reído."},
                    {"pregunta": "Conjuga el verbo 'construir' en pluscuamperfecto de indicativo, primera persona singular (yo).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había construido", "explicacion": "Yo había construido."},
                    {"pregunta": "Conjuga el verbo 'huir' en pluscuamperfecto de indicativo, segunda persona singular (tú).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "habías huido", "explicacion": "Tú habías huido."},
                    {"pregunta": "Conjuga el verbo 'conducir' en pluscuamperfecto de indicativo, tercera persona singular (él/ella/usted).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había conducido", "explicacion": "Él/Ella/Usted había conducido."},
                    {"pregunta": "Conjuga el verbo 'traducir' en pluscuamperfecto de indicativo, primera persona plural (nosotros/as).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "habíamos traducido", "explicacion": "Nosotros/as habíamos traducido."},
                    {"pregunta": "Conjuga el verbo 'traer' en pluscuamperfecto de indicativo, segunda persona plural (vosotros/as).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "habíais traído", "explicacion": "Vosotros/as habíais traído."},
                    {"pregunta": "Conjuga el verbo 'caer' en pluscuamperfecto de indicativo, tercera persona plural (ellos/ellas/ustedes).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "habían caído", "explicacion": "Ellos/Ellas/Ustedes habían caído."},
                    {"pregunta": "Conjuga el verbo 'oír' en pluscuamperfecto de indicativo, primera persona singular (yo).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había oído", "explicacion": "Yo había oído."},
                    {"pregunta": "Conjuga el verbo 'satisfacer' en pluscuamperfecto de indicativo, segunda persona singular (tú).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "habías satisfecho", "explicacion": "Tú habías satisfecho."},
                    {"pregunta": "Conjuga el verbo 'caber' en pluscuamperfecto de indicativo, tercera persona singular (él/ella/usted).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había cabido", "explicacion": "Él/Ella/Usted había cabido."},
                    {"pregunta": "Conjuga el verbo 'valer' en pluscuamperfecto de indicativo, primera persona plural (nosotros/as).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "habíamos valido", "explicacion": "Nosotros/as habíamos valido."},
                    {"pregunta": "Conjuga el verbo 'ser' en pluscuamperfecto de indicativo, primera persona singular (yo).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había sido", "explicacion": "Yo había sido."},
                    {"pregunta": "Conjuga el verbo 'estar' en pluscuamperfecto de indicativo, segunda persona singular (tú).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "habías estado", "explicacion": "Tú habías estado."},
                    {"pregunta": "Conjuga el verbo 'dar' en pluscuamperfecto de indicativo, tercera persona singular (él/ella/usted).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había dado", "explicacion": "Él/Ella/Usted había dado."},
                    {"pregunta": "Conjuga el verbo 'haber' en pluscuamperfecto de indicativo, primera persona singular (yo).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había habido", "explicacion": "Siempre 'había habido' para la forma impersonal 'haber'."},
                    {"pregunta": "Conjuga el verbo 'querer' en pluscuamperfecto de indicativo, primera persona singular (yo).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había querido", "explicacion": "Yo había querido."},
                    {"pregunta": "Conjuga el verbo 'andar' en pluscuamperfecto de indicativo, primera persona singular (yo).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había andado", "explicacion": "Yo había andado."},
                    {"pregunta": "Conjuga el verbo 'contar' en pluscuamperfecto de indicativo, primera persona singular (yo).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había contado", "explicacion": "Yo había contado."},
                    {"pregunta": "Conjuga el verbo 'dormir' en pluscuamperfecto de subjuntivo, primera persona singular (yo).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "hubiera dormido", "explicacion": "Que yo hubiera dormido."},
                    {"pregunta": "Conjuga el verbo 'sentir' en pluscuamperfecto de subjuntivo, segunda persona singular (tú).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "hubieras sentido", "explicacion": "Que tú hubieras sentido."},
                    {"pregunta": "Conjuga el verbo 'pedir' en pluscuamperfecto de subjuntivo, tercera persona singular (él/ella/usted).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "hubiera pedido", "explicacion": "Que él/ella/usted hubiera pedido."},
                    {"pregunta": "Conjuga el verbo 'morir' en pluscuamperfecto de subjuntivo, primera persona plural (nosotros/as).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "hubiéramos muerto", "explicacion": "Que nosotros/as hubiéramos muerto."},
                    {"pregunta": "Conjuga el verbo 'preferir' en pluscuamperfecto de subjuntivo, segunda persona plural (vosotros/as).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "hubierais preferido", "explicacion": "Que vosotros/as hubierais preferido."},
                    {"pregunta": "Conjuga el verbo 'reír' en pluscuamperfecto de subjuntivo, tercera persona plural (ellos/ellas/ustedes).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "hubieran reído", "explicacion": "Que ellos/ellas/ustedes hubieran reído."},
                    {"pregunta": "Conjuga el verbo 'construir' en pluscuamperfecto de subjuntivo, primera persona singular (yo).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "hubiera construido", "explicacion": "Que yo hubiera construido."},
                    {"pregunta": "Conjuga el verbo 'huir' en pluscuamperfecto de subjuntivo, segunda persona singular (tú).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "hubieras huido", "explicacion": "Que tú hubieras huido."},
                    {"pregunta": "Conjuga el verbo 'conducir' en pluscuamperfecto de subjuntivo, tercera persona singular (él/ella/usted).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "hubiera conducido", "explicacion": "Que él/ella/usted hubiera conducido."},
                    {"pregunta": "Conjuga el verbo 'traducir' en pluscuamperfecto de subjuntivo, primera persona plural (nosotros/as).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "hubiéramos traducido", "explicacion": "Que nosotros/as hubiéramos traducido."},
                    {"pregunta": "Conjuga el verbo 'traer' en pluscuamperfecto de subjuntivo, segunda persona plural (vosotros/as).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "hubierais traído", "explicacion": "Que vosotros/as hubierais traído."},
                    {"pregunta": "Conjuga el verbo 'caer' en pluscuamperfecto de subjuntivo, tercera persona plural (ellos/ellas/ustedes).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "hubieran caído", "explicacion": "Que ellos/ellas/ustedes hubieran caído."},
                    {"pregunta": "Conjuga el verbo 'oír' en pluscuamperfecto de subjuntivo, primera persona singular (yo).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "hubiera oído", "explicacion": "Que yo hubiera oído."},
                    {"pregunta": "Conjuga el verbo 'satisfacer' en pluscuamperfecto de subjuntivo, segunda persona singular (tú).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "hubieras satisfecho", "explicacion": "Que tú hubieras satisfecho."},
                    {"pregunta": "Conjuga el verbo 'caber' en pluscuamperfecto de subjuntivo, tercera persona singular (él/ella/usted).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "hubiera cabido", "explicacion": "Que él/ella/usted hubiera cabido."},
                    {"pregunta": "Conjuga el verbo 'valer' en pluscuamperfecto de subjuntivo, primera persona plural (nosotros/as).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "hubiéramos valido", "explicacion": "Que nosotros/as hubiéramos valido."},
                    {"pregunta": "Conjuga el verbo 'ser' en pluscuamperfecto de subjuntivo, primera persona singular (yo).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "hubiera sido", "explicacion": "Que yo hubiera sido."},
                    {"pregunta": "Conjuga el verbo 'estar' en pluscuamperfecto de subjuntivo, segunda persona singular (tú).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "hubieras estado", "explicacion": "Que tú hubieras estado."},
                    {"pregunta": "Conjuga el verbo 'dar' en pluscuamperfecto de subjuntivo, tercera persona singular (él/ella/usted).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "hubiera dado", "explicacion": "Que él/ella/usted hubiera dado."},
                    {"pregunta": "Conjuga el verbo 'haber' en pluscuamperfecto de subjuntivo, primera persona singular (yo).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "hubiera habido", "explicacion": "Que yo hubiera habido."},
                    {"pregunta": "Conjuga el verbo 'querer' en pluscuamperfecto de subjuntivo, primera persona singular (yo).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "hubiera querido", "explicacion": "Que yo hubiera querido."},
                    {"pregunta": "Conjuga el verbo 'andar' en pluscuamperfecto de subjuntivo, primera persona singular (yo).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "hubiera andado", "explicacion": "Que yo hubiera andado."},
                    {"pregunta": "Conjuga el verbo 'contar' en pluscuamperfecto de subjuntivo, primera persona singular (yo).", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "hubiera contado", "explicacion": "Que yo hubiera contado."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Antes de venir aquí, yo ya [terminar] mi tarea.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había terminado", "explicacion": "La acción de terminar fue antes de venir."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Cuando llegamos, la película ya [empezar].'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había empezado", "explicacion": "La película empezó antes de nuestra llegada."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Ellos [viajar] a París antes de la pandemia.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "habían viajado", "explicacion": "El viaje fue anterior a la pandemia."},
                    {"pregunta": "Completa con pluscuamperfecto: 'No reconocí a María porque [cambiar] mucho.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había cambiado", "explicacion": "El cambio ocurrió antes de que la reconociera."},
                    {"pregunta": "Completa con pluscuamperfecto: 'El profesor ya [explicar] el tema cuando llegué.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había explicado", "explicacion": "La explicación fue antes de mi llegada."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Nunca [ver] tanta gente en ese lugar.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había visto", "explicacion": "La acción de ver fue anterior al momento de la narración."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Ella me dijo que [llamar] a su madre.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había llamado", "explicacion": "La llamada fue anterior a que ella me lo dijera."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Cuando me desperté, mi hermano ya [salir].'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había salido", "explicacion": "Mi hermano salió antes de que me despertara."},
                    {"pregunta": "Corrige: 'Antes del examen, yo estudié mucho.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Antes del examen, yo había estudiado mucho.", "explicacion": "La acción de estudiar fue anterior al examen."},
                    {"pregunta": "Corrige: 'Al llegar, el tren partió.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Al llegar, el tren ya había partido.", "explicacion": "El tren partió antes de mi llegada."},
                    {"pregunta": "Corrige: 'Ellos comieron cuando terminaron de jugar.' (Usa pluscuamperfecto para la primera acción)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Ellos comieron cuando ya habían terminado de jugar.", "explicacion": "Comer fue después de haber terminado de jugar."},
                    {"pregunta": "Corrige: 'La encontré y me dijo que fue un buen día.' (Usa pluscuamperfecto para la acción anterior)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "La encontré y me dijo que había sido un buen día.", "explicacion": "El día fue bueno antes de que ella me lo dijera."},
                    {"pregunta": "Contextualiza: 'Cuando regresó, la ciudad [cambiar] por completo.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Cuando regresó, la ciudad había cambiado por completo.", "explicacion": "El cambio ocurrió antes de su regreso."},
                    {"pregunta": "Contextualiza: 'No pude entrar porque la puerta [cerrar] con llave.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "No pude entrar porque la puerta había cerrado con llave.", "explicacion": "La puerta se cerró antes de que intentara entrar."},
                    {"pregunta": "Contextualiza: 'El descubrimiento fue crucial; los científicos [buscar] la cura por años.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "El descubrimiento fue crucial; los científicos habían buscado la cura por años.", "explicacion": "La búsqueda fue anterior al descubrimiento."},
                    {"pregunta": "Contextualiza: 'Antes de su accidente, él [ser] un atleta famoso.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Antes de su accidente, él había sido un atleta famoso.", "explicacion": "Su fama fue anterior al accidente."},
                    {"pregunta": "Transforma: 'Después de que el sol se puso, cenamos.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Después de que el sol se había puesto, cenamos.", "explicacion": "El sol se puso antes de la cena."},
                    {"pregunta": "Transforma: 'Ella visitó el museo antes.' (Usa pluscuamperfecto con un contexto de tiempo)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Ella ya había visitado el museo.", "explicacion": "Implica que la visita fue antes de un momento determinado en el pasado."},
                    {"pregunta": "Corrige: 'Pensé que ya hice mi trabajo.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Pensé que ya había hecho mi trabajo.", "explicacion": "La acción de hacer el trabajo fue antes del pensamiento."},
                    {"pregunta": "Contextualiza: 'La casa estaba vacía; sus habitantes [irse] hace horas.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "La casa estaba vacía; sus habitantes se habían ido hace horas.", "explicacion": "La partida ocurrió antes de que la casa estuviera vacía."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Nos dimos cuenta de que [olvidar] las llaves.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "habíamos olvidado", "explicacion": "El olvido fue antes de darnos cuenta."},
                    {"pregunta": "Completa con pluscuamperfecto: 'La nieve [derretirse] antes de que llegara la primavera.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "se había derretido", "explicacion": "La nieve se derritió antes de la primavera."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Creí que [entender] la lección, pero no fue así.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había entendido", "explicacion": "La acción de entender fue antes de la creencia."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Cuando despertó, el desayuno ya [preparar].'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había sido preparado", "explicacion": "El desayuno fue preparado antes de que despertara."},
                    {"pregunta": "Corrige: 'Cuando llegué, el concierto terminó.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Cuando llegué, el concierto ya había terminado.", "explicacion": "El concierto terminó antes de mi llegada."},
                    {"pregunta": "Corrige: 'Me dijo que ella no vio la película.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Me dijo que ella no había visto la película.", "explicacion": "La acción de no ver fue anterior a que me lo dijera."},
                    {"pregunta": "Contextualiza: 'El atleta estaba exhausto porque [correr] una maratón.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "El atleta estaba exhausto porque había corrido una maratón.", "explicacion": "Correr la maratón fue la causa de su agotamiento."},
                    {"pregunta": "Contextualiza: 'Los árboles estaban secos; nadie [regar] las plantas.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Los árboles estaban secos; nadie había regado las plantas.", "explicacion": "No regar las plantas fue anterior a que los árboles estuvieran secos."},
                    {"pregunta": "Transforma: 'Él aprendió la lección después de que cometió el error.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Él aprendió la lección después de que había cometido el error.", "explicacion": "El error fue cometido antes de aprender la lección."},
                    {"pregunta": "Transforma: 'Nunca fui a Madrid antes de 2010.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Nunca había ido a Madrid antes de 2010.", "explicacion": "La no visita fue anterior a 2010."},
                    {"pregunta": "Completa con pluscuamperfecto: 'El médico descubrió que [tener] una enfermedad rara.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había tenido", "explicacion": "Tener la enfermedad fue anterior al descubrimiento."},
                    {"pregunta": "Completa con pluscuamperfecto: 'El niño [perder] su juguete antes de llegar al parque.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había perdido", "explicacion": "Perder el juguete fue antes de llegar al parque."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Ayer supe que [aprobar] el examen.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había aprobado", "explicacion": "Aprobar el examen fue antes de que lo supiera."},
                    {"pregunta": "Corrige: 'Yo vi la película y me gustó.' (Usa pluscuamperfecto para la acción anterior si aplicable)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Yo ya había visto la película y me gustó.", "explicacion": "El pluscuamperfecto enfatiza que la vi antes de un momento específico en el pasado."},
                    {"pregunta": "Contextualiza: 'La reunión se pospuso porque el director [enfermarse].' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "La reunión se pospuso porque el director se había enfermado.", "explicacion": "Enfermarse fue la causa del aplazamiento."},
                    {"pregunta": "Contextualiza: 'En el momento del choque, yo [cruzar] la calle.' (Usa pluscuamperfecto si la acción fue completada antes del choque)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "En el momento del choque, yo ya había cruzado la calle.", "explicacion": "Cruzar la calle fue antes del choque."},
                    {"pregunta": "Transforma: 'Terminamos de comer y fuimos al cine.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Después de que habíamos terminado de comer, fuimos al cine.", "explicacion": "La acción de terminar de comer fue anterior a ir al cine."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Pensaron que [escapar] los prisioneros.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "habían escapado", "explicacion": "El escape fue antes de que ellos pensaran."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Me di cuenta de que [perder] la cartera.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había perdido", "explicacion": "La pérdida de la cartera fue antes de darme cuenta."},
                    {"pregunta": "Corrige: 'Ella me contó que visitó ese lugar.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Ella me contó que había visitado ese lugar.", "explicacion": "La visita fue anterior a que me lo contara."},
                    {"pregunta": "Contextualiza: 'El edificio se derrumbó porque [construir] mal.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "El edificio se derrumbó porque había sido construido mal.", "explicacion": "La mala construcción fue anterior al derrumbe."},
                    {"pregunta": "Transforma: 'Llovió antes de que saliéramos.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Ya había llovido antes de que saliéramos.", "explicacion": "La lluvia fue anterior a nuestra salida."},
                    {"pregunta": "Completa con pluscuamperfecto: 'La fiesta [terminar] cuando llegamos.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había terminado", "explicacion": "La fiesta terminó antes de nuestra llegada."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Me informó que ya [recibir] el paquete.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había recibido", "explicacion": "Recibir el paquete fue antes de que me informara."},
                    {"pregunta": "Corrige: 'Yo le dije que ya leí el libro.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Yo le dije que ya había leído el libro.", "explicacion": "Leer el libro fue antes de que yo se lo dijera."},
                    {"pregunta": "Contextualiza: 'El coche no arrancaba porque [quedarse] sin gasolina.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "El coche no arrancaba porque se había quedado sin gasolina.", "explicacion": "Quedarse sin gasolina fue la causa de que no arrancara."},
                    {"pregunta": "Transforma: 'Después de que ella se despidió, lloré.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Después de que ella se había despedido, lloré.", "explicacion": "Despedirse fue antes de llorar."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Cuando lo vi, ya [saber] la verdad.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había sabido", "explicacion": "Saber la verdad fue antes de verlo."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Llegamos a la estación, pero el tren ya [partir].'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había partido", "explicacion": "El tren partió antes de nuestra llegada."},
                    {"pregunta": "Corrige: 'Me arrepentí de lo que hice.' (Usa pluscuamperfecto para la acción anterior)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Me arrepentí de lo que había hecho.", "explicacion": "Hacer fue antes de arrepentirse."},
                    {"pregunta": "Contextualiza: 'El equipo ganó porque [entrenar] muy duro.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "El equipo ganó porque había entrenado muy duro.", "explicacion": "El entrenamiento fue la causa de la victoria."},
                    {"pregunta": "Transforma: 'Antes de que te llamara, cené.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Antes de que te llamara, ya había cenado.", "explicacion": "Cenar fue antes de llamar."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Ella me dijo que [pensar] mucho en eso.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había pensado", "explicacion": "Pensar fue antes de que ella me lo dijera."},
                    {"pregunta": "Completa con pluscuamperfecto: 'La tormenta [empezar] antes de que saliéramos.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había empezado", "explicacion": "La tormenta empezó antes de nuestra salida."},
                    {"pregunta": "Corrige: 'Cuando lo visité, él ya se fue.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Cuando lo visité, él ya se había ido.", "explicacion": "Irse fue antes de la visita."},
                    {"pregunta": "Contextualiza: 'Mi padre no quería ir porque [estar] enfermo.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Mi padre no quería ir porque había estado enfermo.", "explicacion": "Estar enfermo fue la causa de su negativa."},
                    {"pregunta": "Transforma: 'Al abrir la caja, vi que alguien la abrió antes.' (Usa pluscuamperfecto para la acción anterior)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Al abrir la caja, vi que alguien la había abierto antes.", "explicacion": "La acción de abrir la caja fue anterior a que yo la abriera."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Cuando despertó, el sol ya [salir].'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había salido", "explicacion": "El sol salió antes de que despertara."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Ellos se dieron cuenta de que [cometer] un error.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "habían cometido", "explicacion": "El error fue cometido antes de que se dieran cuenta."},
                    {"pregunta": "Corrige: 'Yo fui al cine y ya la vi.' (Usa pluscuamperfecto para la acción anterior si aplica)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Yo fui al cine, pero ya la había visto.", "explicacion": "Ver la película fue antes de ir al cine."},
                    {"pregunta": "Contextualiza: 'La comida estaba fría porque [pasar] mucho tiempo.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "La comida estaba fría porque había pasado mucho tiempo.", "explicacion": "El tiempo pasó antes de que la comida se enfriara."},
                    {"pregunta": "Transforma: 'Terminaron de limpiar antes de que la visita llegara.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Habían terminado de limpiar antes de que la visita llegara.", "explicacion": "La limpieza fue anterior a la llegada de la visita."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Pensaba que [perder] el partido.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había perdido", "explicacion": "Perder el partido fue antes de que lo pensara."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Antes de ese día, nunca [nevar] tanto.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había nevado", "explicacion": "La nieve fue anterior a ese día."},
                    {"pregunta": "Corrige: 'Descubrimos que él no dijo la verdad.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Descubrimos que él no había dicho la verdad.", "explicacion": "No decir la verdad fue anterior al descubrimiento."},
                    {"pregunta": "Contextualiza: 'El concierto fue un éxito porque los músicos [practicar] mucho.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "El concierto fue un éxito porque los músicos habían practicado mucho.", "explicacion": "La práctica fue la causa del éxito."},
                    {"pregunta": "Transforma: 'Llamó después de que yo salí.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Llamó después de que yo había salido.", "explicacion": "Yo salí antes de que él llamara."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Cuando llegué al trabajo, mi jefe ya [ir] a una reunión.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había ido", "explicacion": "Ir a la reunión fue antes de mi llegada al trabajo."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Ellos [ver] la película la semana anterior.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "habían visto", "explicacion": "Ver la película fue antes del momento de la narración."},
                    {"pregunta": "Corrige: 'Yo ya comí cuando ella llegó.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Yo ya había comido cuando ella llegó.", "explicacion": "Comer fue antes de su llegada."},
                    {"pregunta": "Contextualiza: 'El paciente mejoró porque [tomar] su medicina a tiempo.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "El paciente mejoró porque había tomado su medicina a tiempo.", "explicacion": "Tomar la medicina fue la causa de la mejoría."},
                    {"pregunta": "Transforma: 'El ladrón escapó antes de que la policía llegara.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "El ladrón ya había escapado antes de que la policía llegara.", "explicacion": "El escape fue anterior a la llegada de la policía."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Ella me preguntó si [conocer] a Pedro.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había conocido", "explicacion": "Conocer a Pedro fue antes de que me preguntara."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Al abrir la carta, supo que su amiga [escribir] hacía mucho.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había escrito", "explicacion": "Escribir la carta fue antes de que ella la abriera."},
                    {"pregunta": "Corrige: 'El museo cerró cuando nosotros entramos.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "El museo ya había cerrado cuando nosotros entramos.", "explicacion": "El cierre fue anterior a nuestra entrada."},
                    {"pregunta": "Contextualiza: 'Estaban cansados porque [caminar] todo el día.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Estaban cansados porque habían caminado todo el día.", "explicacion": "Caminar fue la causa del cansancio."},
                    {"pregunta": "Transforma: 'Leí el libro antes de ver la película.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Había leído el libro antes de ver la película.", "explicacion": "Leer el libro fue anterior a ver la película."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Cuando llegué al aeropuerto, mi vuelo ya [salir].'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había salido", "explicacion": "El vuelo salió antes de mi llegada al aeropuerto."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Nos dijeron que [probar] esa comida antes.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "habíamos probado", "explicacion": "Probar la comida fue antes de que nos lo dijeran."},
                    {"pregunta": "Corrige: 'Yo vi ese programa la semana pasada y me gustó.' (Usa pluscuamperfecto si ya lo había visto antes del momento de la narración)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Yo ya había visto ese programa la semana pasada y me gustó.", "explicacion": "Enfatiza que la acción de ver fue anterior al punto de referencia pasado."},
                    {"pregunta": "Contextualiza: 'El jardín estaba inundado porque [llover] mucho.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "El jardín estaba inundado porque había llovido mucho.", "explicacion": "La lluvia fue la causa de la inundación."},
                    {"pregunta": "Transforma: 'Me quedé dormido después de que leí el libro.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Me quedé dormido después de que había leído el libro.", "explicacion": "Leer el libro fue antes de quedarse dormido."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Ellos [ganar] la competencia el año anterior.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "habían ganado", "explicacion": "Ganar la competencia fue antes del año actual."},
                    {"pregunta": "Completa con pluscuamperfecto: 'La casa que [comprar] resultó ser muy grande.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había comprado", "explicacion": "La compra de la casa fue anterior a que resultara ser grande."},
                    {"pregunta": "Corrige: 'Pensé que ya pagué la cuenta.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Pensé que ya había pagado la cuenta.", "explicacion": "Pagar la cuenta fue antes de que lo pensara."},
                    {"pregunta": "Contextualiza: 'El vaso se rompió porque [caer] al suelo.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "El vaso se rompió porque había caído al suelo.", "explicacion": "Caer al suelo fue la causa de que se rompiera."},
                    {"pregunta": "Transforma: 'Comenzamos el proyecto después de que el director lo aprobó.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Comenzamos el proyecto después de que el director lo había aprobado.", "explicacion": "La aprobación fue anterior al inicio del proyecto."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Cuando llegué, ellos ya [cenar].'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "habían cenado", "explicacion": "Cenar fue antes de mi llegada."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Él dijo que [viajar] a muchos países.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había viajado", "explicacion": "Viajar fue antes de que lo dijera."},
                    {"pregunta": "Corrige: 'Yo ya hice la cama cuando mi madre entró.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Yo ya había hecho la cama cuando mi madre entró.", "explicacion": "Hacer la cama fue antes de que mi madre entrara."},
                    {"pregunta": "Contextualiza: 'La fábrica cerró porque [tener] problemas financieros.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "La fábrica cerró porque había tenido problemas financieros.", "explicacion": "Los problemas financieros fueron la causa del cierre."},
                    {"pregunta": "Transforma: 'Me enteré de la noticia después de que él me lo contó.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Me enteré de la noticia después de que él me lo había contado.", "explicacion": "Contar la noticia fue antes de que me enterara."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Nunca [estar] en un lugar tan hermoso.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había estado", "explicacion": "La acción de estar fue anterior al momento de la narración."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Ellos [descubrir] la verdad mucho antes.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "habían descubierto", "explicacion": "El descubrimiento fue anterior al momento de la narración."},
                    {"pregunta": "Corrige: 'Cuando lo llamé, él ya se fue.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Cuando lo llamé, él ya se había ido.", "explicacion": "Irse fue antes de la llamada."},
                    {"pregunta": "Contextualiza: 'El libro me aburrió porque ya [leer] la historia.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "El libro me aburrió porque ya había leído la historia.", "explicacion": "Leer la historia fue la causa del aburrimiento."},
                    {"pregunta": "Transforma: 'El alumno reprobó porque no estudió.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "El alumno reprobó porque no había estudiado.", "explicacion": "No estudiar fue la causa de reprobar."},
                    {"pregunta": "Completa con pluscuamperfecto: 'La gente ya [llegar] cuando empezó el evento.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había llegado", "explicacion": "Llegar la gente fue antes del inicio del evento."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Me dijo que [comprar] un coche nuevo.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había comprado", "explicacion": "Comprar el coche fue antes de que me lo dijera."},
                    {"pregunta": "Corrige: 'Cuando llegué, mi madre cocinó la cena.' (Usa pluscuamperfecto si la cena ya estaba hecha)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Cuando llegué, mi madre ya había cocinado la cena.", "explicacion": "Cenar fue antes de mi llegada."},
                    {"pregunta": "Contextualiza: 'La planta se murió porque [recibir] demasiada agua.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "La planta se murió porque había recibido demasiada agua.", "explicacion": "Recibir demasiada agua fue la causa de que muriera la planta."},
                    {"pregunta": "Transforma: 'Terminamos el proyecto y lo entregamos.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Después de que habíamos terminado el proyecto, lo entregamos.", "explicacion": "Terminar el proyecto fue antes de entregarlo."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Los turistas se dieron cuenta de que [perder] el mapa.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "habían perdido", "explicacion": "Perder el mapa fue antes de darse cuenta."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Nunca [pensar] que eso pasaría.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había pensado", "explicacion": "Pensar fue anterior al suceso."},
                    {"pregunta": "Corrige: 'Me dijo que ya vio esa película.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Me dijo que ya había visto esa película.", "explicacion": "Ver la película fue anterior a que me lo dijera."},
                    {"pregunta": "Contextualiza: 'La mesa estaba sucia porque nadie [limpiar].' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "La mesa estaba sucia porque nadie había limpiado.", "explicacion": "No limpiar fue la causa de la suciedad."},
                    {"pregunta": "Transforma: 'Él llegó después de que yo me fui.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Él llegó después de que yo me había ido.", "explicacion": "Irse fue antes de que él llegara."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Cuando lo encontramos, el perro [escapar] de casa.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había escapado", "explicacion": "Escapar de casa fue anterior a encontrarlo."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Ellos [descubrir] el tesoro hace mucho tiempo.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "habían descubierto", "explicacion": "Descubrir el tesoro fue hace mucho tiempo, anterior al momento de la narración."},
                    {"pregunta": "Corrige: 'Cuando entró, el programa ya comenzó.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Cuando entró, el programa ya había comenzado.", "explicacion": "El programa comenzó antes de que él entrara."},
                    {"pregunta": "Contextualiza: 'La ventana estaba rota porque [caer] una piedra.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "La ventana estaba rota porque había caído una piedra.", "explicacion": "La caída de la piedra fue la causa de que se rompiera la ventana."},
                    {"pregunta": "Transforma: 'Compré la casa después de que la vi.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Compré la casa después de que la había visto.", "explicacion": "Ver la casa fue antes de comprarla."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Nos dimos cuenta de que la lluvia [parar].'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había parado", "explicacion": "La lluvia paró antes de darnos cuenta."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Los estudiantes [entregar] sus proyectos antes de la fecha límite.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "habían entregado", "explicacion": "Entregar los proyectos fue antes de la fecha límite."},
                    {"pregunta": "Corrige: 'Ella me confesó que ella no lo hizo.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Ella me confesó que ella no lo había hecho.", "explicacion": "No hacer algo fue anterior a la confesión."},
                    {"pregunta": "Contextualiza: 'Estaba muy feliz porque [recibir] buenas noticias.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Estaba muy feliz porque había recibido buenas noticias.", "explicacion": "Recibir noticias fue la causa de su felicidad."},
                    {"pregunta": "Transforma: 'Después de que el sol salió, salimos a caminar.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Después de que el sol había salido, salimos a caminar.", "explicacion": "El sol salió antes de salir a caminar."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Cuando regresamos, la casa [pintar] de otro color.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había sido pintada", "explicacion": "La casa fue pintada antes de nuestro regreso."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Los niños [jugar] todo el día y estaban agotados.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "habían jugado", "explicacion": "Jugar fue la causa del agotamiento."},
                    {"pregunta": "Corrige: 'Supe que ella ya cenó.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Supe que ella ya había cenado.", "explicacion": "Cenar fue antes de que lo supiera."},
                    {"pregunta": "Contextualiza: 'El concierto se suspendió porque [vender] pocas entradas.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "El concierto se suspendió porque se habían vendido pocas entradas.", "explicacion": "La venta de pocas entradas fue la causa de la suspensión."},
                    {"pregunta": "Transforma: 'Él me dijo que vio una película interesante.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Él me dijo que había visto una película interesante.", "explicacion": "Ver la película fue anterior a que me lo dijera."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Antes del viaje, ellos [comprar] todos los boletos.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "habían comprado", "explicacion": "Comprar los boletos fue antes del viaje."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Me sorprendió que [venir] tanta gente.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "hubiera venido", "explicacion": "La llegada de la gente fue anterior a la sorpresa (subjuntivo)."},
                    {"pregunta": "Corrige: 'Ellos ya llegaron cuando yo salí.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Ellos ya habían llegado cuando yo salí.", "explicacion": "Llegar fue antes de que yo saliera."},
                    {"pregunta": "Contextualiza: 'El árbol se cayó porque [estar] viejo.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "El árbol se cayó porque había estado viejo.", "explicacion": "Estar viejo fue la causa de la caída."},
                    {"pregunta": "Transforma: 'Después de que el sol se ocultó, las estrellas aparecieron.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Después de que el sol se había ocultado, las estrellas aparecieron.", "explicacion": "Ocultarse el sol fue antes de la aparición de las estrellas."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Pensábamos que el problema [resolver].'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había sido resuelto", "explicacion": "El problema fue resuelto antes de que lo pensáramos."},
                    {"pregunta": "Completa con pluscuamperfecto: 'La carta [llegar] antes de lo esperado.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había llegado", "explicacion": "La llegada de la carta fue antes de lo esperado."},
                    {"pregunta": "Corrige: 'Me dijo que no le gustó la comida.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Me dijo que no le había gustado la comida.", "explicacion": "No gustarle la comida fue anterior a que me lo dijera."},
                    {"pregunta": "Contextualiza: 'Estábamos tristes porque [perder] la oportunidad.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Estábamos tristes porque habíamos perdido la oportunidad.", "explicacion": "Perder la oportunidad fue la causa de la tristeza."},
                    {"pregunta": "Transforma: 'Ellos se sorprendieron al ver que yo terminé la tarea.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Ellos se sorprendieron al ver que yo había terminado la tarea.", "explicacion": "Terminar la tarea fue anterior a su sorpresa."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Nunca [imaginar] que fuera posible.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había imaginado", "explicacion": "Imaginar fue anterior al momento de la narración."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Cuando llegamos, la tienda ya [cerrar].'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había cerrado", "explicacion": "Cerrar la tienda fue antes de nuestra llegada."},
                    {"pregunta": "Corrige: 'Me contaron que su abuelo murió el año pasado.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Me contaron que su abuelo había muerto el año pasado.", "explicacion": "Morir el abuelo fue anterior a que me lo contaran."},
                    {"pregunta": "Contextualiza: 'El coche estaba sucio porque [llover] durante la noche.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "El coche estaba sucio porque había llovido durante la noche.", "explicacion": "La lluvia fue la causa de la suciedad."},
                    {"pregunta": "Transforma: 'Nos duchamos después de que terminamos de correr.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Nos duchamos después de que habíamos terminado de correr.", "explicacion": "Terminar de correr fue antes de ducharse."},
                    {"pregunta": "Completa con pluscuamperfecto: 'El libro que [leer] era muy interesante.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había leído", "explicacion": "La lectura fue anterior al momento de la narración."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Ella me confesó que [romper] el jarrón.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había roto", "explicacion": "Romper el jarrón fue anterior a la confesión."},
                    {"pregunta": "Corrige: 'Yo ya comí cuando ellos llegaron.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Yo ya había comido cuando ellos llegaron.", "explicacion": "Comer fue antes de su llegada."},
                    {"pregunta": "Contextualiza: 'La casa estaba en silencio porque todos [irse] a dormir.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "La casa estaba en silencio porque todos se habían ido a dormir.", "explicacion": "Irse a dormir fue la causa del silencio."},
                    {"pregunta": "Transforma: 'Me di cuenta de que ella mintió.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Me di cuenta de que ella había mentido.", "explicacion": "Mentir fue antes de darme cuenta."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Cuando lo llamé, él ya [salir] de la oficina.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había salido", "explicacion": "Salir de la oficina fue antes de la llamada."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Nunca [visitar] un lugar tan exótico.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había visitado", "explicacion": "Visitar fue anterior al momento de la narración."},
                    {"pregunta": "Corrige: 'Ella me dijo que encontró su perro.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Ella me dijo que había encontrado su perro.", "explicacion": "Encontrar el perro fue anterior a que me lo dijera."},
                    {"pregunta": "Contextualiza: 'El atleta no pudo competir porque [lesionarse].' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "El atleta no pudo competir porque se había lesionado.", "explicacion": "Lesionarse fue la causa de no poder competir."},
                    {"pregunta": "Transforma: 'Comí cuando ella se fue.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Comí cuando ella ya se había ido.", "explicacion": "Irse fue antes de comer."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Me contó que [viajar] a Europa el año pasado.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había viajado", "explicacion": "Viajar fue anterior a que me lo contara."},
                    {"pregunta": "Completa con pluscuamperfecto: 'Pensé que [terminar] el trabajo.'", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "había terminado", "explicacion": "Terminar el trabajo fue antes de que lo pensara."},
                    {"pregunta": "Corrige: 'Cuando llegaron, la película comenzó.' (Usa pluscuamperfecto)", "tipo": "Conjugación verbal (Pluscuamperfecto)", "respuesta": "Cuando llegaron, la película ya había comenzado.", "explicacion": "La película comenzó antes de su llegada."}
                ]
            }
        }
    }


def normalizar_respuesta(respuesta):
    """Normaliza una respuesta para comparación (quitar espacios, minúsculas)."""
    if isinstance(respuesta, str):
        return respuesta.strip().lower()
    return respuesta

def comparar_respuestas(respuesta_usuario, respuesta_correcta):
    """Compara la respuesta del usuario con la respuesta correcta."""
    return normalizar_respuesta(respuesta_usuario) == normalizar_respuesta(respuesta_correcta)

def iniciar_practica_consola():
    """Inicia la práctica de lengua castellana en consola."""
    ejercicios_castellano = cargar_ejercicios_pluscuamperfecto()
    
    # Nos enfocamos solo en los ejercicios de Pluscuamperfecto
    ejercicios_pluscuamperfecto = ejercicios_castellano["Morfología"]["Intermedio"]["Conjugación verbal (Pluscuamperfecto)"]
    
    if not ejercicios_pluscuamperfecto:
        print("No hay ejercicios de pluscuamperfecto disponibles.")
        return

    random.shuffle(ejercicios_pluscuamperfecto) # Mezclar los ejercicios

    puntuacion = 0
    resultados = []

    print("\n--- ¡Bienvenido a la Práctica de Conjugación Verbal (Pluscuamperfecto)! ---")
    print(f"Tienes {len(ejercicios_pluscuamperfecto)} ejercicios para practicar.\n")

    for i, ejercicio in enumerate(ejercicios_pluscuamperfecto):
        print(f"\n--- Ejercicio {i + 1} de {len(ejercicios_pluscuamperfecto)} ---")
        print(f"Pregunta: {ejercicio['pregunta']}")
        
        respuesta_usuario = input("Tu respuesta: ").strip()

        es_correcta = comparar_respuestas(respuesta_usuario, ejercicio['respuesta'])

        if es_correcta:
            print("¡Correcto! ✅")
            puntuacion += 1
        else:
            print("Incorrecto. ❌")
        
        print(f"La respuesta correcta era: {ejercicio['respuesta']}")
        print(f"Explicación: {ejercicio['explicacion']}")
        
        resultados.append({
            "pregunta": ejercicio['pregunta'],
            "tu_respuesta": respuesta_usuario,
            "correcta": es_correcta,
            "respuesta_correcta": ejercicio['respuesta'],
            "explicacion": ejercicio['explicacion']
        })

    print("\n--- Práctica Terminada ---")
    print(f"Has obtenido {puntuacion} de {len(ejercicios_pluscuamperfecto)} respuestas correctas.")
    print("\n--- Resumen de Resultados ---")
    for res in resultados:
        estado = "✅ CORRECTO" if res['correcta'] else "❌ INCORRECTO"
        print(f"\nPregunta: {res['pregunta']}")
        print(f"Tu respuesta: {res['tu_respuesta']}")
        print(f"Respuesta correcta: {res['respuesta_correcta']}")
        print(f"Estado: {estado}")
        print(f"Explicación: {res['explicacion']}")
    
    print("\n¡Gracias por practicar!")

if __name__ == "__main__":
    iniciar_practica_consola()
