#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Práctica de Inglés — Séptimo Grado (Tkinter GUI)

Características:
- Banco de ejercicios (100) con: oración en inglés, traducción, explicación y ejemplo.
- Interfaz gráfica con Tkinter: navegar entre ejercicios, pedir traducción, mostrar respuesta y explicación.
- Modo libre: añadir frases propias (inglés + traducción) y guardarlas en un archivo.
- Guardado de frases personalizadas en 'frases_personalizadas.txt'.

Ejecuta: python3 practica_ingles_7_tkinter.py
"""

import tkinter as tk
from tkinter import ttk, messagebox, scrolledtext, simpledialog
import random
import difflib
import unicodedata
import string
import os

# ======================
# Datos: 100 ejercicios
# (Usamos la misma colección detallada que creamos anteriormente.)
# Cada entrada es un diccionario con keys: id, topic, english, spanish, explanation, example
# ======================
exercises = [
    {"id": 1, "topic": "Present Simple", "english": "She works at the university.",
     "spanish": "Ella trabaja en la universidad.",
     "explanation": "Uso del presente simple para hábitos o verdades generales (tercera persona: +s).",
     "example": "He works in a bank. -> Él trabaja en un banco."},
    {"id": 2, "topic": "Present Continuous", "english": "They are studying for the exams.",
     "spanish": "Ellos están estudiando para los exámenes.",
     "explanation": "Presente continuo para acciones en progreso ahora o en un periodo actual.",
     "example": "I am reading a book. -> Estoy leyendo un libro."},
    {"id": 3, "topic": "Past Simple", "english": "I visited London last summer.",
     "spanish": "Visité Londres el verano pasado.",
     "explanation": "Pasado simple para acciones completadas en un tiempo concreto en el pasado.",
     "example": "She called me yesterday. -> Ella me llamó ayer."},
    {"id": 4, "topic": "Past Continuous", "english": "He was reading when the phone rang.",
     "spanish": "Él estaba leyendo cuando sonó el teléfono.",
     "explanation": "Pasado continuo para una acción en curso interrumpida por otra acción.",
     "example": "They were talking while I prepared dinner. -> Estaban hablando mientras yo preparaba la cena."},
    {"id": 5, "topic": "Present Perfect", "english": "She has finished her homework.",
     "spanish": "Ella ha terminado su tarea.",
     "explanation": "Present perfect para acciones que tienen relevancia en el presente o resultado reciente.",
     "example": "I have just eaten. -> Acabo de comer."},
    {"id": 6, "topic": "Present Perfect (duración)", "english": "I have lived here for five years.",
     "spanish": "He vivido aquí durante cinco años.",
     "explanation": "Se usa 'have/has + past participle' para expresar duración hasta el presente.",
     "example": "She has worked here since 2018. -> Ella ha trabajado aquí desde 2018."},
    {"id": 7, "topic": "Past Perfect", "english": "By the time we arrived, the film had started.",
     "spanish": "Para cuando llegamos, la película ya había empezado.",
     "explanation": "Past perfect indica que una acción ocurrió antes de otra en el pasado.",
     "example": "He had left before I called. -> Él se había ido antes de que llamara."},
    {"id": 8, "topic": "Will (future)", "english": "I will help you with your project.",
     "spanish": "Te ayudaré con tu proyecto.",
     "explanation": "'Will' para predicciones, decisiones espontáneas o promesas.",
     "example": "I'll open the door. -> Abriré la puerta."},
    {"id": 9, "topic": "Going to (future plan)", "english": "They are going to travel to Canada next month.",
     "spanish": "Ellos van a viajar a Canadá el próximo mes.",
     "explanation": "'Be going to' para planes o intenciones futuras.",
     "example": "I'm going to study tonight. -> Voy a estudiar esta noche."},
    {"id": 10, "topic": "Future Continuous", "english": "This time tomorrow I will be flying to Madrid.",
     "spanish": "A esta hora mañana estaré volando a Madrid.",
     "explanation": "Future continuous para acciones que estarán en progreso en un momento futuro.",
     "example": "At 8pm she'll be having dinner. -> A las 8 estará cenando."},
    {"id": 11, "topic": "Modal: can", "english": "She can speak three languages.",
     "spanish": "Ella puede hablar tres idiomas.",
     "explanation": "'Can' expresa habilidad o posibilidad.",
     "example": "I can swim. -> Puedo nadar."},
    {"id": 12, "topic": "Modal: could", "english": "When I was young I could run fast.",
     "spanish": "Cuando era joven, podía correr rápido.",
     "explanation": "'Could' expresa habilidad en el pasado o posibilidad/petición educada.",
     "example": "Could you help me? -> ¿Podrías ayudarme?"},
    {"id": 13, "topic": "Modal: might/may", "english": "It might rain this afternoon.",
     "spanish": "Podría llover esta tarde.",
     "explanation": "'Might' y 'may' expresan posibilidad.",
     "example": "She may come later. -> Ella podría venir más tarde."},
    {"id": 14, "topic": "Modal: must", "english": "You must wear a helmet when riding a bike.",
     "spanish": "Debes llevar casco cuando montes en bicicleta.",
     "explanation": "'Must' expresa obligación o deducción fuerte.",
     "example": "You must stop at a red light. -> Debes parar en un semáforo en rojo."},
    {"id": 15, "topic": "Have to (obligation)", "english": "I have to attend the meeting tomorrow.",
     "spanish": "Tengo que asistir a la reunión mañana.",
     "explanation": "'Have to' indica obligación externa o necesidad.",
     "example": "She has to finish the report. -> Ella tiene que terminar el informe."},
    {"id": 16, "topic": "Should (advice)", "english": "You should study more for the test.",
     "spanish": "Deberías estudiar más para la prueba.",
     "explanation": "'Should' para dar consejos o recomendaciones.",
     "example": "You should see a doctor. -> Deberías ver a un médico."},
    {"id": 17, "topic": "Would (polite)", "english": "Would you pass the salt, please?",
     "spanish": "¿Podrías pasarme la sal, por favor?",
     "explanation": "'Would' se usa para peticiones educadas o condicionales.",
     "example": "Would you help me? -> ¿Me ayudarías?"},
    {"id": 18, "topic": "Used to (past habit)", "english": "I used to play tennis every weekend.",
     "spanish": "Solía jugar tenis todos los fines de semana.",
     "explanation": "'Used to' para hábitos en el pasado que ya no ocurren.",
     "example": "He used to smoke. -> Solía fumar."},
    {"id": 19, "topic": "Needn't (no necessity)", "english": "You needn't come if you're busy.",
     "spanish": "No necesitas venir si estás ocupado.",
     "explanation": "'Needn't' expresa que no hay necesidad de hacer algo.",
     "example": "You needn't worry. -> No necesitas preocuparte."},
    {"id": 20, "topic": "Ought to (advice)", "english": "You ought to apologize.",
     "spanish": "Deberías disculparte.",
     "explanation": "'Ought to' es similar a 'should' para aconsejar.",
     "example": "You ought to check the facts. -> Deberías verificar los hechos."},
    {"id": 21, "topic": "Zero conditional", "english": "If you heat water to 100°C, it boils.",
     "spanish": "Si calientas agua a 100°C, hierve.",
     "explanation": "Zero conditional para verdades científicas o hechos generales.",
     "example": "If you mix red and blue, you get purple. -> Si mezclas rojo y azul, obtienes morado."},
    {"id": 22, "topic": "First conditional", "english": "If it rains, we will cancel the picnic.",
     "spanish": "Si llueve, cancelaremos el picnic.",
     "explanation": "First conditional para situaciones reales o posibles en el futuro.",
     "example": "If I see her, I'll tell her. -> Si la veo, le diré."},
    {"id": 23, "topic": "Second conditional", "english": "If I won the lottery, I would travel the world.",
     "spanish": "Si ganara la lotería, viajaría por el mundo.",
     "explanation": "Second conditional para situaciones hipotéticas en el presente o futuro.",
     "example": "If I were rich, I would buy a house. -> Si fuera rico, compraría una casa."},
    {"id": 24, "topic": "Third conditional", "english": "If I had known, I would have called you.",
     "spanish": "Si lo hubiera sabido, te habría llamado.",
     "explanation": "Third conditional para hipótesis en el pasado que no ocurrieron.",
     "example": "If she had studied, she would have passed. -> Si ella hubiera estudiado, habría aprobado."},
    {"id": 25, "topic": "Mixed conditional", "english": "If I had studied medicine, I would be a doctor now.",
     "spanish": "Si hubiera estudiado medicina, ahora sería médico.",
     "explanation": "Mixed conditional combina pasado hipotético con resultado presente.",
     "example": "If I had saved money, I would be traveling now. -> Si hubiera ahorrado, estaría viajando ahora."},
    {"id": 26, "topic": "Passive (present simple)", "english": "The book is written by a famous author.",
     "spanish": "El libro está escrito por un autor famoso.",
     "explanation": "Pasiva para enfatizar el objeto o cuando el sujeto no es importante.",
     "example": "The letter is sent every Monday. -> La carta se envía todos los lunes."},
    {"id": 27, "topic": "Passive (past simple)", "english": "The cake was baked by my grandmother.",
     "spanish": "El pastel fue horneado por mi abuela.",
     "explanation": "Pasiva en pasado simple para hechos pasados.",
     "example": "The house was built in 1990. -> La casa fue construida en 1990."},
    {"id": 28, "topic": "Passive with modals", "english": "The problem must be solved immediately.",
     "spanish": "El problema debe ser resuelto de inmediato.",
     "explanation": "Uso de modales en voz pasiva para expresar necesidad u obligación.",
     "example": "The documents should be signed. -> Los documentos deberían ser firmados."},
    {"id": 29, "topic": "Get-passive", "english": "He got injured during the match.",
     "spanish": "Se lesionó durante el partido.",
     "explanation": "'Get' en voz pasiva se usa con frecuencia para acontecimientos inesperados.",
     "example": "She got promoted last month. -> Ella fue ascendida el mes pasado."},
    {"id": 30, "topic": "Passive (future)", "english": "The house will be painted next week.",
     "spanish": "La casa será pintada la próxima semana.",
     "explanation": "Pasiva en futuro para acciones que se realizarán.",
     "example": "The results will be announced tomorrow. -> Los resultados serán anunciados mañana."},
    {"id": 31, "topic": "Reported speech (statements)", "english": "She said, 'I am tired'.",
     "spanish": "Ella dijo que estaba cansada.",
     "explanation": "En estilo indirecto, los tiempos verbales suelen retroceder (present -> past).",
     "example": "He said, 'I live here.' -> He said he lived there. -> Él dijo que vivía allí."},
    {"id": 32, "topic": "Reported speech (questions)", "english": "He asked, 'Where do you live?'",
     "spanish": "Él preguntó dónde vivías.",
     "explanation": "Las preguntas en estilo indirecto cambian la estructura y normalmente retroceden el tiempo.",
     "example": "She asked, 'What is your name?' -> She asked what my name was. -> Ella preguntó cómo me llamaba."},
    {"id": 33, "topic": "Reported commands", "english": "The teacher told him, 'Open the window'.",
     "spanish": "La profesora le dijo que abriera la ventana.",
     "explanation": "Los mandatos en estilo indirecto suelen ir con 'told + object + to' o con subjuntivo en traducción.",
     "example": "He told me, 'Sit down.' -> He told me to sit down. -> Me dijo que me sentara."},
    {"id": 34, "topic": "Reported suggestions", "english": "She suggested, 'Let's go to the cinema'.",
     "spanish": "Ella sugirió ir al cine.",
     "explanation": "'Let's' en estilo indirecto se transforma según el verbo de reporte.",
     "example": "They suggested, 'We should start early.' -> They suggested starting early. -> Sugirieron empezar temprano."},
    {"id": 35, "topic": "Gerunds", "english": "I enjoy swimming in the sea.",
     "spanish": "Disfruto nadar en el mar.",
     "explanation": "Algunos verbos (enjoy, avoid, consider...) requieren gerundio (-ing).",
     "example": "She enjoys singing. -> Ella disfruta cantar."},
    {"id": 36, "topic": "Infinitives", "english": "He decided to study abroad.",
     "spanish": "Él decidió estudiar en el extranjero.",
     "explanation": "Algunos verbos son seguidos por infinitivo (decide, promise, hope...).",
     "example": "They hope to arrive soon. -> Esperan llegar pronto."},
    {"id": 37, "topic": "Gerund vs Infinitive", "english": "She stopped smoking last year.",
     "spanish": "Ella dejó de fumar el año pasado.",
     "explanation": "'Stop + gerund' significa dejar un hábito; 'stop + to' significa parar para hacer otra cosa.",
     "example": "He stopped to answer the phone. -> Paró para contestar el teléfono."},
    {"id": 38, "topic": "Verbs + gerund", "english": "They avoided speaking about politics.",
     "spanish": "Ellos evitaron hablar sobre política.",
     "explanation": "Avoid + gerund: evitar hacer algo.",
     "example": "She avoided answering the question. -> Evitó responder la pregunta."},
    {"id": 39, "topic": "Verbs + infinitive", "english": "He promised to call me.",
     "spanish": "Él prometió llamarme.",
     "explanation": "Promised + infinitive: promesa de realizar una acción.",
     "example": "They agreed to help. -> Acordaron ayudar."},
    {"id": 40, "topic": "Causative: make/let", "english": "She made him apologize.",
     "spanish": "Ella lo obligó a disculparse.",
     "explanation": "Make + object + base form: obligar a alguien a hacer algo.",
     "example": "The teacher made the students rewrite the essay. -> La profesora obligó a los alumnos a reescribir el ensayo."},
    {"id": 41, "topic": "Phrasal verb: give up", "english": "Don't give up, keep trying.",
     "spanish": "No te rindas, sigue intentándolo.",
     "explanation": "Give up = rendirse; separable phrasal verb.",
     "example": "He gave up smoking. -> Él dejó de fumar."},
    {"id": 42, "topic": "Phrasal verb: look forward to", "english": "I look forward to meeting you.",
     "spanish": "Espero con ilusión conocerte.",
     "explanation": "'Look forward to' va seguido de gerundio (meeting).",
     "example": "We look forward to seeing you. -> Esperamos verte con ilusión."},
    {"id": 43, "topic": "Phrasal verb: put off", "english": "They put off the meeting until next week.",
     "spanish": "Aplazaron la reunión hasta la próxima semana.",
     "explanation": "Put off = posponer/aplazar.",
     "example": "Don't put off your homework. -> No postergues tu tarea."},
    {"id": 44, "topic": "Phrasal verb: take off", "english": "The plane took off on time.",
     "spanish": "El avión despegó a tiempo.",
     "explanation": "Take off = despegar (avión) o quitarse (ropa).",
     "example": "He took off his coat. -> Se quitó el abrigo."},
    {"id": 45, "topic": "Phrasal verb: run out of", "english": "We've run out of milk.",
     "spanish": "Se nos ha acabado la leche.",
     "explanation": "Run out of = quedarse sin algo.",
     "example": "We've run out of time. -> Se nos ha acabado el tiempo."},
    {"id": 46, "topic": "Phrasal verb: turn down", "english": "He turned down the job offer.",
     "spanish": "Rechazó la oferta de trabajo.",
     "explanation": "Turn down = rechazar o bajar (volumen).",
     "example": "She turned down the invitation. -> Rechazó la invitación."},
    {"id": 47, "topic": "Phrasal verb: carry out", "english": "Scientists carried out the experiment.",
     "spanish": "Los científicos realizaron el experimento.",
     "explanation": "Carry out = llevar a cabo/realizar.",
     "example": "They carried out the survey. -> Realizaron la encuesta."},
    {"id": 48, "topic": "Phrasal verb: set up", "english": "They set up the new laboratory.",
     "spanish": "Instalaron el nuevo laboratorio.",
     "explanation": "Set up = montar, instalar, establecer.",
     "example": "He set up a meeting. -> Organizó una reunión."},
    {"id": 49, "topic": "Phrasal verb: look after", "english": "She looks after her little brother.",
     "spanish": "Ella cuida a su hermanito.",
     "explanation": "Look after = cuidar de alguien.",
     "example": "Can you look after my cat? -> ¿Puedes cuidar mi gato?"},
    {"id": 50, "topic": "Phrasal verb: break down", "english": "The car broke down on the highway.",
     "spanish": "El coche se averió en la autopista.",
     "explanation": "Break down = averiarse o descomponerse.",
     "example": "My laptop broke down yesterday. -> Mi portátil se averió ayer."},
    {"id": 51, "topic": "Relative clause (defining)", "english": "The student who studies hard will pass the exam.",
     "spanish": "El estudiante que estudia mucho aprobará el examen.",
     "explanation": "Oración de relativo especificativa: 'who' añade información esencial.",
     "example": "The book that you lent me is interesting. -> El libro que me prestaste es interesante."},
    {"id": 52, "topic": "Relative clause (non-defining)", "english": "Paris, which is the capital of France, is beautiful.",
     "spanish": "París, que es la capital de Francia, es hermosa.",
     "explanation": "Oración de relativo explicativa: va entre comas y aporta información adicional.",
     "example": "My car, which is blue, is new. -> Mi coche, que es azul, es nuevo."},
    {"id": 53, "topic": "Comparatives", "english": "My sister is taller than me.",
     "spanish": "Mi hermana es más alta que yo.",
     "explanation": "Comparatives para comparar cualidades entre dos elementos.",
     "example": "This book is cheaper than that one. -> Este libro es más barato que ese."},
    {"id": 54, "topic": "Superlatives", "english": "This is the most interesting book I've ever read.",
     "spanish": "Este es el libro más interesante que he leído.",
     "explanation": "Superlatives indican el grado máximo dentro de un grupo.",
     "example": "She is the tallest in the class. -> Ella es la más alta de la clase."},
    {"id": 55, "topic": "Adverbs vs Adjectives", "english": "She speaks English fluently.",
     "spanish": "Ella habla inglés con fluidez.",
     "explanation": "'Fluently' es un adverbio que modifica al verbo 'speaks'.",
     "example": "He is quick (adjective). He runs quickly (adverb). -> Él es rápido. Él corre rápidamente."},
    {"id": 56, "topic": "Countable vs Uncountable", "english": "There is much information in the article.",
     "spanish": "Hay mucha información en el artículo.",
     "explanation": "Information es incontable; usamos 'much' en inglés y 'mucha' en español.",
     "example": "There are many books. -> Hay muchos libros."},
    {"id": 57, "topic": "Quantifiers", "english": "Few students attended the lecture.",
     "spanish": "Pocos estudiantes asistieron a la conferencia.",
     "explanation": "Few indica una cantidad pequeña (contable).",
     "example": "A few students came. -> Unos pocos estudiantes vinieron."},
    {"id": 58, "topic": "Articles", "english": "I bought an apple and the book I wanted.",
     "spanish": "Compré una manzana y el libro que quería.",
     "explanation": "Uso de 'an' para sustantivos indefinidos y 'the' para algo específico.",
     "example": "I saw a cat. The cat was black. -> Vi un gato. El gato era negro."},
    {"id": 59, "topic": "Unless", "english": "I won't go unless you come with me.",
     "spanish": "No iré a menos que vengas conmigo.",
     "explanation": "'Unless' equivale a 'if not' (a menos que).",
     "example": "I won't buy it unless it's cheap. -> No lo compraré a menos que sea barato."},
    {"id": 60, "topic": "Inversion for emphasis", "english": "Never have I seen such a beautiful sight.",
     "spanish": "Nunca había visto un paisaje tan hermoso.",
     "explanation": "Inversión con adverbios negativos para enfatizar; en español normalmente se mantiene orden normal.",
     "example": "Rarely do we get such opportunities. -> Rara vez tenemos tales oportunidades."},
    {"id": 61, "topic": "It's time + subjunctive", "english": "It's time you cleaned your room.",
     "spanish": "Es hora de que limpies tu habitación.",
     "explanation": "'It's time' + pasado suburbial/should para indicar que ya es hora de hacer algo.",
     "example": "It's time we left. -> Es hora de que nos vayamos."},
    {"id": 62, "topic": "Prepositions of time", "english": "She was born in July.",
     "spanish": "Ella nació en julio.",
     "explanation": "'In' para meses y años.",
     "example": "He was born in 1990. -> Él nació en 1990."},
    {"id": 63, "topic": "Prepositions of place", "english": "The keys are on the table.",
     "spanish": "Las llaves están sobre la mesa.",
     "explanation": "'On' indica superficie; 'in' dentro de algo.",
     "example": "The cat is under the bed. -> El gato está debajo de la cama."},
    {"id": 64, "topic": "Collocations", "english": "I need to make a decision today.",
     "spanish": "Necesito tomar una decisión hoy.",
     "explanation": "Make a decision es una colocación correcta (no *do a decision).",
     "example": "Make a choice -> Tomar una decisión."},
    {"id": 65, "topic": "Formal writing", "english": "Please find attached the report.",
     "spanish": "Adjunto encontrará el informe.",
     "explanation": "Frases formales usadas en correos o cartas profesionales.",
     "example": "Please find attached the agenda. -> Adjunto encontrará la agenda."},
    {"id": 66, "topic": "Academic vocabulary", "english": "The results indicate a significant improvement.",
     "spanish": "Los resultados indican una mejora significativa.",
     "explanation": "Vocabulario formal típico en textos científicos o académicos.",
     "example": "The data show an increase. -> Los datos muestran un aumento."},
    {"id": 67, "topic": "Passive with agent", "english": "The song was written by John.",
     "spanish": "La canción fue escrita por John.",
     "explanation": "La voz pasiva puede incluir el agente con 'by'.",
     "example": "The report was prepared by the team. -> El informe fue preparado por el equipo."},
    {"id": 68, "topic": "Direct speech (future)", "english": "They said, 'We will arrive at noon'.",
     "spanish": "Dijeron: 'Llegaremos al mediodía'.",
     "explanation": "Traducción literal de estilo directo; en estilo indirecto el tiempo puede retroceder.",
     "example": "He said, 'I will call you.' -> Dijo: 'Te llamaré'."},
    {"id": 69, "topic": "Wish + past", "english": "I wish I had more free time.",
     "spanish": "Ojalá tuviera más tiempo libre.",
     "explanation": "'Wish' + pasado para expresar deseo de una situación presente diferente.",
     "example": "I wish I knew the answer. -> Ojalá supiera la respuesta."},
    {"id": 70, "topic": "Used to (negative)", "english": "She didn't use to like coffee.",
     "spanish": "A ella no le gustaba el café.",
     "explanation": "Forma negativa para hábitos pasados: 'didn't use to'.",
     "example": "He didn't use to go out much. -> Él no solía salir mucho."},
    {"id": 71, "topic": "Tag questions", "english": "You're coming, aren't you?",
     "spanish": "Vienes, ¿verdad?",
     "explanation": "Tag questions para confirmar información; se traducen con preguntas cortas.",
     "example": "She can't drive, can she? -> Ella no puede conducir, ¿verdad?"},
    {"id": 72, "topic": "Agreement short answers", "english": "So do I.",
     "spanish": "Yo también.",
     "explanation": "Formas cortas para estar de acuerdo con una afirmación previa.",
     "example": "I like coffee. So do I. -> Me gusta el café. Yo también."},
    {"id": 73, "topic": "Neither (agreement)", "english": "Neither did I.",
     "spanish": "Yo tampoco.",
     "explanation": "'Neither' se usa para mostrar acuerdo con una negación previa.",
     "example": "I don't like it. Neither do I. -> No me gusta. Yo tampoco."},
    {"id": 74, "topic": "Time clauses", "english": "After she graduates, she will start working.",
     "spanish": "Después de que se gradúe, empezará a trabajar.",
     "explanation": "Cláusulas temporales con conjunciones (after, before, when...).",
     "example": "Before I leave, I'll call you. -> Antes de irme, te llamaré."},
    {"id": 75, "topic": "Exclamations", "english": "What a beautiful house!",
     "spanish": "¡Qué casa más hermosa!",
     "explanation": "Exclamaciones para expresar sorpresa o emoción.",
     "example": "What a pity! -> ¡Qué pena!"},
    {"id": 76, "topic": "Emphasis do", "english": "I do like that movie.",
     "spanish": "Realmente me gusta esa pel
