def display_menu():
    print("1. Mostrar consejos en español")
    print("2. Show tips in English")
    print("3. Salir")

def show_tips(language):
    if language == "es":
        tips = [
            "Acentuación: Familiarízate con las palabras agudas, llanas y esdrújulas.",
            "Signos de puntuación: Coloca correctamente puntos, comas y otros signos.",
            "Reglas de ortografía: Conoce cuándo usar 'b' o 'v', 'c', 'k' o 'q', 'g' o 'j', 'll' o 'y'.",
            "Figuras retóricas: Explora recursos estilísticos para enriquecer tus textos.",
            "Evita la repetición innecesaria de palabras.",
            "Utiliza conectores para enlazar ideas.",
            "Escribe párrafos con una sola idea principal.",
            "Usa la puntuación correctamente.",
            "Evita oraciones demasiado largas.",
            "Revisa la ortografía y gramática.",
            "Evita el uso de jerga técnica innecesaria.",
            "Escribe en un tono adecuado para tu audiencia.",
            "Usa ejemplos para clarificar puntos complejos.",
            "Mantén la coherencia en el tiempo verbal.",
            "Utiliza sinónimos para evitar la repetición.",
            "Evita el uso excesivo de adjetivos y adverbios.",
            "Asegúrate de que cada oración aporte algo nuevo.",
            "Elimina las palabras innecesarias.",
            "Utiliza la voz activa cuando sea posible.",
            "Revisa tu texto en busca de ambigüedades.",
            "No mezcles diferentes estilos de redacción.",
            "Usa citas textuales solo cuando sea necesario.",
            "Evita los clichés y frases hechas.",
            "Mantén la estructura lógica en el desarrollo de ideas.",
            "Revisa la consistencia en la terminología utilizada.",
            "Utiliza transiciones suaves entre párrafos.",
            "Evita el uso excesivo de comillas.",
            "Usa las comillas para enfatizar palabras o frases clave.",
            "No abuses de los signos de exclamación.",
            "Escribe en forma positiva en lugar de negativa.",
            "Divide las oraciones complejas en dos o más oraciones simples.",
            "Evita el uso de palabras redundantes.",
            "Escribe con precisión y exactitud.",
            "Asegúrate de que el sujeto y el verbo concuerden en número.",
            "Utiliza un lenguaje inclusivo y no sexista.",
            "Revisa la coherencia de las metáforas y símiles.",
            "Evita las dobles negaciones.",
            "Usa el subjuntivo correctamente en situaciones hipotéticas.",
            "Evita la vaguedad y la ambigüedad.",
            "Sé consistente en el uso de mayúsculas.",
            "Usa la puntuación para guiar al lector.",
            "Revisa el uso de preposiciones.",
            "Evita los cambios bruscos de tema.",
            "Asegúrate de que las citas estén bien atribuidas.",
            "Usa un estilo coherente en todo el texto.",
            "No repitas la misma idea en diferentes palabras.",
            "Evita los modismos y expresiones coloquiales en textos formales.",
            "Utiliza la primera persona solo cuando sea apropiado.",
            "Mantén la objetividad en la escritura académica.",
            "Revisa la coherencia en el uso de citas y referencias.",
            "Utiliza listas numeradas para enumerar puntos.",
            "Usa las viñetas para resaltar puntos importantes.",
            "Escribe un buen título que refleje el contenido del texto.",
            "Revisa la estructura de las oraciones subordinadas.",
            "Evita el uso de frases largas y complejas sin necesidad.",
            "Asegúrate de que cada párrafo tenga una idea central clara.",
            "Evita el uso excesivo de siglas y abreviaturas.",
            "Mantén el mismo punto de vista a lo largo del texto.",
            "Evita el uso de palabras demasiado técnicas sin explicación.",
            "Utiliza un lenguaje formal en documentos académicos y profesionales.",
            "Usa la voz pasiva solo cuando sea necesario.",
            "Revisa la concordancia entre sustantivos y adjetivos.",
            "Asegúrate de que el pronombre se refiera claramente a su antecedente.",
            "Usa los adverbios con moderación.",
            "Mantén la coherencia en la estructura de las listas.",
            "Revisa la consistencia en el uso de tiempos verbales.",
            "Evita el uso de palabras rebuscadas o arcaicas.",
            "Usa las citas indirectas para parafrasear ideas de otros.",
            "Evita las palabras de relleno.",
            "Utiliza la negrita para destacar información clave.",
            "Usa el subrayado con moderación.",
            "No olvides incluir referencias y bibliografía en textos académicos.",
            "Asegúrate de que las imágenes y tablas estén bien etiquetadas.",
            "Revisa la correcta numeración de páginas y secciones.",
            "Evita las oraciones incompletas.",
            "Usa las notas al pie de página para aclaraciones importantes.",
            "Evita las generalizaciones excesivas.",
            "Revisa la coherencia en el uso de comillas simples y dobles.",
            "Asegúrate de que las citas textuales estén correctamente formateadas.",
            "Usa el paréntesis para incluir información adicional sin interrumpir el flujo del texto.",
            "Evita el uso de pronombres ambiguos.",
            "Mantén la coherencia en la estructura gramatical de las oraciones.",
            "Usa la cursiva para enfatizar palabras o títulos de obras.",
            "Revisa la consistencia en el uso de abreviaturas.",
            "Evita el uso de verbos débiles como hacer o tener.",
            "Usa la segunda persona solo en textos de tono informal.",
            "Revisa la coherencia en la numeración de ejemplos y figuras.",
            "Evita el uso excesivo de metáforas.",
            "Usa el estilo directo en lugar del indirecto cuando sea posible.",
            "Asegúrate de que las ideas principales estén claramente resaltadas.",
            "Revisa la coherencia en la numeración de capítulos y secciones.",
            "Evita las digresiones innecesarias",
            "Usa los puntos suspensivos con moderación.",
            "Asegúrate de que el título del texto sea claro y conciso.",
            "Evita el uso excesivo de oraciones interrogativas en textos formales.",
            "Revisa la consistencia en el uso de mayúsculas y minúsculas.",
            "Evita el uso de palabras o frases redundantes.",
            "Usa un lenguaje preciso y específico.",
            "Revisa la coherencia en el uso de los títulos y subtítulos.",
            "Asegúrate de que el texto fluya naturalmente de una idea a otra.",
        ]
    else:
        tips = [
            "Accentuation: Familiarize yourself with acute, grave, and proparoxytone words.",
            "Punctuation marks: Place periods, commas, and other punctuation marks correctly.",
            "Spelling rules: Understand when to use 'b' or 'v', 'c', 'k' or 'q', 'g' or 'j', 'll' or 'y'.",
            "Rhetorical figures: Explore stylistic resources to enrich your texts.",
            "Avoid unnecessary repetition of words.",
            "Use connectors to link ideas.",
            "Write paragraphs with a single main idea.",
            "Use punctuation correctly.",
            "Avoid overly long sentences.",
            "Check spelling and grammar.",
            "Avoid unnecessary technical jargon.",
            "Write in a tone appropriate for your audience.",
            "Use examples to clarify complex points.",
            "Maintain consistency in verb tense.",
            "Use synonyms to avoid repetition.",
            "Avoid overusing adjectives and adverbs.",
            "Ensure each sentence adds something new.",
            "Eliminate unnecessary words.",
            "Use the active voice whenever possible.",
            "Review your text for ambiguities.",
            "Do not mix different writing styles.",
            "Use direct quotes only when necessary.",
            "Avoid clichés and set phrases.",
            "Maintain a logical structure in the development of ideas.",
            "Check consistency in the terminology used.",
            "Use smooth transitions between paragraphs.",
            "Avoid overusing quotation marks.",
            "Use quotation marks to emphasize key words or phrases.",
            "Do not overuse exclamation marks.",
            "Write in a positive form instead of a negative one.",
            "Divide complex sentences into two or more simple sentences.",
            "Avoid using redundant words.",
            "Write with precision and accuracy.",
            "Ensure that the subject and verb agree in number.",
            "Use inclusive and non-sexist language.",
            "Review the coherence of metaphors and similes.",
            "Avoid double negatives.",
            "Use the subjunctive correctly in hypothetical situations.",
            "Avoid vagueness and ambiguity.",
            "Be consistent in the use of capital letters.",
            "Use punctuation to guide the reader.",
            "Review the use of prepositions.",
            "Avoid abrupt changes in topic.",
            "Ensure quotes are properly attributed.",
            "Use a consistent style throughout the text.",
            "Do not repeat the same idea in different words.",
            "Avoid idioms and colloquial expressions in formal texts.",
            "Use the first person only when appropriate.",
            "Maintain objectivity in academic writing.",
            "Check consistency in the use of citations and references.",
            "Use numbered lists to enumerate points.",
            "Use bullet points to highlight important points.",
            "Write a good title that reflects the content of the text.",
            "Review the structure of subordinate sentences.",
            "Avoid using long and complex phrases unnecessarily.",
            "Ensure each paragraph has a clear central idea.",
            "Avoid overusing acronyms and abbreviations.",
            "Maintain the same point of view throughout the text.",
            "Avoid using overly technical words without explanation.",
            "Use formal language in academic and professional documents.",
            "Use the passive voice only when necessary.",
            "Review the agreement between nouns and adjectives.",
            "Ensure that the pronoun clearly refers to its antecedent.",
            "Use adverbs sparingly.",
            "Maintain consistency in the structure of lists.",
            "Check consistency in the use of verb tenses.",
            "Avoid using convoluted or archaic words.",
            "Use indirect quotes to paraphrase others' ideas.",
            "Avoid filler words.",
            "Use bold to highlight key information.",
            "Use underlining sparingly.",
            "Do not forget to include references and bibliography in academic texts.",
            "Ensure images and tables are well-labeled.",
            "Check the correct numbering of pages and sections.",
            "Use footnotes for important clarifications.",
            "Avoid excessive generalizations.",
            "Check consistency in the use of single and double quotation marks.",
            "Ensure direct quotes are properly formatted.",
            "Use parentheses to include additional information without interrupting the text's flow.",
            "Avoid ambiguous pronouns.",
            "Maintain consistency in the grammatical structure of sentences.",
            "Use italics to emphasize words or titles of works.",
            "Check consistency in the use of abbreviations.",
            "Avoid using weak verbs like do or have.",
            "Use the second person only in informal texts.",
            "Check consistency in the numbering of examples and figures.",
            "Avoid overusing metaphors.",
            "Use direct style instead of indirect style when possible.",
            "Ensure the main ideas are clearly highlighted.",
            "Check consistency in the numbering of chapters and sections.",
            "Avoid unnecessary digressions.",
            "Use ellipses sparingly.",
            "Ensure the title of the text is clear and concise.",
            "Avoid overusing interrogative sentences in formal texts.",
            "Check consistency in the use of upper and lower case.",
            "Avoid using redundant words or phrases.",
            "Use precise and specific language.",
            "Check consistency in the use of titles and subtitles.",
            "Ensure the text flows naturally from one idea to another.",
        ]

    for tip in tips:
        print(tip)

def main():
    while True:
        display_menu()
        choice = input("Selecciona una opción (1/2/3): ")

        if choice == "1":
            show_tips("es")
        elif choice == "2":
            show_tips("en")
        elif choice == "3":
            print("¡Hasta luego!")
            break
        else:
            print("Opción inválida. Inténtalo de nuevo.")

if __name__ == "__main__":
    main()
