# Lista de oraciones con adjetivos en Lengua Castellana
oraciones = [
    "Nos sirvió un camarero joven poco amistoso.",
    "Era una habitación incómoda, sucia y oscura.",
    "Usó una navaja grande afilada.",
    "Nos encontramos en una enorme sala de conferencias de cristal.",
    "Rompió un precioso plato blanco de porcelana japonesa.",
    "Susan salía con un atractivo estadounidense alto y moreno.",
    "Tenía un bonito perrito blanco de pelo rizado.",
    "Conocimos a un joven atractivo teniente de navio.",
    "La joven vivia sola en una bonita habitation limpia y clara.",
    "Se bebio un enorme vaso de leche helada.",
    "Llevaba un bolso de cuero negro grande y reluciente",
    "Era una mesa de cocina, de madera, hecha a mano.",
    "Fuimos a un pequeño restaurante italiano muy bonito.",
    "En la muñeca llevaba una pulsera de esmeraldas de un verde oscuro.",
    "En la casita vivía una vieja gruñona.",
    "El Sr.Martin estaba hablando con una bella mujer joven.",
    "Las dos familias vivían en una vieja choza decrepita.",
    "Vimos una película vieja",
    "Tenía unos ojos grandes, rojos, saltones.",
    "Era un día gris, lluvioso, deprimente.",
    "Tomó una refrescante ducha fría por la manana."
        "El lenguaje de programación Python es altamente programable y adaptable a una variedad de aplicaciones.",
    "La arquitectura modular del sistema facilita la reutilización de componentes en diferentes partes del software.",
    "El algoritmo de búsqueda implementado es altamente eficiente y puede manejar grandes conjuntos de datos en tiempo récord.",
    "El código está organizado de manera estructurada, lo que facilita su comprensión y mantenimiento a largo plazo.",
    "La aplicación sigue un enfoque orientado a objetos, lo que permite una mayor modularidad y reutilización del código.",
    "El diseño de la interfaz de usuario es intuitivo y fácil de usar para los usuarios finales.",
    "La base de datos está diseñada para ser escalable y manejar grandes volúmenes de datos sin comprometer el rendimiento.",
    "El sistema de seguridad implementado garantiza la confidencialidad y la integridad de los datos del usuario.",
    "El framework utilizado proporciona una amplia gama de herramientas y bibliotecas para el desarrollo de aplicaciones web.",
    "La arquitectura cliente-servidor permite una comunicación eficiente entre el cliente y el servidor.",
    "El protocolo de comunicación utilizado garantiza la entrega segura y confiable de los mensajes entre los sistemas.",
    "La interfaz de programación de aplicaciones (API) facilita la integración de diferentes sistemas y servicios.",
    "La infraestructura de nube proporciona escalabilidad y disponibilidad bajo demanda para las aplicaciones.",
    "La interfaz gráfica de usuario (GUI) ofrece una experiencia visual atractiva y funcional para los usuarios.",
    "El entorno de desarrollo integrado (IDE) proporciona herramientas poderosas para escribir, depurar y ejecutar código.",
    "El modelo de desarrollo ágil permite una entrega rápida y iterativa de nuevas funcionalidades.",
    "El sistema de control de versiones facilita la colaboración entre los miembros del equipo y el seguimiento de los cambios.",
    "La metodología de pruebas automatizadas garantiza la calidad y la fiabilidad del software desarrollado.",
    "El motor de base de datos utilizado ofrece un rendimiento óptimo y una gestión eficiente de los datos.",
    "El sistema de gestión de contenido permite la creación y publicación de contenido de manera rápida y sencilla.",
    "La capa de presentación del software proporciona una interfaz amigable y accesible para los usuarios.",
    "El sistema de encriptación utilizado protege la privacidad y la seguridad de la información confidencial.",
    "La arquitectura de microservicios permite la creación y mantenimiento de aplicaciones escalables y modulares.",
    "La herramienta de análisis de datos proporciona información valiosa sobre el comportamiento y las preferencias de los usuarios.",
    "El sistema de gestión de configuración garantiza la consistencia y la integridad de la configuración del sistema.",
    "El servidor de aplicaciones proporciona un entorno seguro y estable para la ejecución de aplicaciones empresariales.",
    "La tecnología de contenedores facilita el despliegue y la gestión de aplicaciones en diferentes entornos.",
    "El sistema de almacenamiento distribuido garantiza la disponibilidad y la redundancia de los datos.",
    "La arquitectura sin servidor permite una escalabilidad automática y una gestión simplificada de la infraestructura.",
    "El marco de desarrollo utilizado proporciona una estructura sólida y flexible para el desarrollo de aplicaciones.",
    "El sistema de indexación de búsqueda facilita la recuperación rápida y precisa de la información.",
    "La herramienta de monitorización proporciona visibilidad y control sobre el rendimiento y la disponibilidad del sistema.",
    "El sistema de gestión de errores identifica y soluciona rápidamente los problemas que surgen durante la ejecución del software.",
    "La arquitectura orientada a servicios permite la integración de sistemas heterogéneos y la interoperabilidad de los datos.",
    "La tecnología de inteligencia artificial proporciona capacidades avanzadas de análisis y predicción en tiempo real.",
    "El sistema de compresión de datos reduce el tamaño de los archivos y acelera la transferencia de datos.",
    "La herramienta de generación de informes permite la creación de informes personalizados y la visualización de datos.",
    "El sistema de gestión de identidades protege los recursos y los datos mediante la autenticación y la autorización.",
    "La capa de acceso a datos proporciona una interfaz uniforme para acceder y manipular los datos almacenados.",
    "La tecnología de blockchain garantiza la integridad y la transparencia de las transacciones en línea.",
    "El sistema de procesamiento de eventos en tiempo real detecta y responde automáticamente a los eventos del sistema.",
    "La herramienta de automatización de procesos optimiza y simplifica las tareas repetitivas y manuales.",
    "El sistema de orquestación de contenedores coordina y gestiona la ejecución de contenedores en un entorno distribuido.",
    "La tecnología de realidad aumentada ofrece experiencias inmersivas y interactivas a los usuarios.",
    "El sistema de gestión de relaciones con los clientes (CRM) mejora la interacción y la satisfacción del cliente.",
    "La arquitectura de eventos permite una comunicación asíncrona y una integración flexible entre los componentes del sistema.",
    "La herramienta de análisis de rendimiento identifica cuellos de botella y optimiza el rendimiento del sistema.",
    "El sistema de almacenamiento en caché mejora el tiempo de respuesta y la escalabilidad del sistema.",
    "La plataforma de colaboración en línea facilita la comunicación y la colaboración entre los miembros del equipo.",
    "El sistema de gestión de la cadena de suministro optimiza la logística y la gestión de inventario.",
    "La tecnología de reconocimiento de voz permite la interacción verbal y el control de dispositivos mediante comandos de voz.",
    "El sistema de gestión de la seguridad de la información protege los datos confidenciales contra amenazas internas y externas.",
    "La herramienta de integración continua automatiza la integración y las pruebas de código para garantizar la calidad del software.",
    "El sistema de monitorización de redes supervisa el tráfico de red y detecta posibles intrusiones o fallos de seguridad.",
    "La tecnología de realidad virtual crea entornos simulados y experiencias inmersivas para los usuarios.",
    "El sistema de gestión de proyectos facilita la planificación, la ejecución y el seguimiento de proyectos.",
    "La herramienta de análisis de datos ofrece insights y recomendaciones basadas en datos para la toma de decisiones empresariales.",
    "El sistema de detección de anomalías identifica patrones inusuales y posibles amenazas en el sistema.",
    "La tecnología de geolocalización permite la identificación de la ubicación física de dispositivos y usuarios.",
    "El sistema de análisis predictivo utiliza modelos estadísticos para prever tendencias y comportamientos futuros.",
    "La herramienta de gestión de la cadena de suministro optimiza la planificación y el seguimiento de la cadena de suministro.",
    "El sistema de gestión de contenidos permite la creación, edición y publicación de contenido de manera colaborativa.",
    "La tecnología de reconocimiento facial identifica y verifica la identidad de individuos mediante análisis biométrico.",
    "El sistema de análisis de riesgos evalúa y gestiona los riesgos asociados con las operaciones empresariales.",
    "La herramienta de gestión de activos digitales organiza y gestiona activos digitales como imágenes, vídeos y documentos.",
    "El sistema de gestión de eventos captura, procesa y analiza eventos en tiempo real para la toma de decisiones.",
    "La tecnología de aprendizaje automático permite a los sistemas aprender y mejorar automáticamente a partir de datos.",
    "El sistema de gestión de documentos digitaliza y organiza documentos físicos para facilitar el acceso y la colaboración.",
    "La herramienta de automatización de marketing simplifica y optimiza las campañas de marketing y la generación de leads.",
    "El sistema de gestión de la cadena de suministro garantiza la entrega oportuna y eficiente de productos y servicios.",
    "La tecnología de análisis de sentimientos evalúa el tono y el sentimiento de los comentarios y publicaciones en línea.",
    "El sistema de gestión de la experiencia del cliente mejora la satisfacción y la fidelidad del cliente mediante la personalización.",
    "La herramienta de planificación de recursos empresariales integra y gestiona los procesos empresariales en una plataforma unificada.",
    "El sistema de análisis de datos en tiempo real proporciona insights inmediatos sobre el comportamiento del usuario y las tendencias del mercado.",
    "La tecnología de reconocimiento óptico de caracteres convierte imágenes y documentos escaneados en texto editable.",
    "El sistema de gestión de la cadena de suministro optimiza la planificación, el transporte y el almacenamiento de productos.",
    "La herramienta de análisis de big data procesa y analiza grandes volúmenes de datos para identificar patrones y tendencias.",
    "El sistema de gestión de la relación con el cliente (CRM) centraliza y gestiona las interacciones con los clientes.",
    "La tecnología de análisis de redes sociales analiza la actividad y la interacción en las redes sociales para comprender el comportamiento del usuario.",
    "El sistema de gestión de la calidad garantiza el cumplimiento de los estándares de calidad y la satisfacción del cliente.",
    "La herramienta de gestión de proyectos facilita la colaboración y el seguimiento de tareas en equipos distribuidos.",
    "El sistema de análisis de datos en la nube proporciona capacidades de análisis escalables y flexibles en la nube.",
    "La tecnología de reconocimiento de voz permite la interacción con dispositivos mediante comandos de voz.",
    "El sistema de gestión de inventario optimiza el seguimiento y la reposición de productos en el almacén.",
    "La herramienta de análisis de datos ofrece insights accionables para mejorar la toma de decisiones empresariales.",
    "El sistema de gestión de flotas optimiza la planificación y el seguimiento de vehículos y activos móviles.",
    "La tecnología de análisis de datos en tiempo real proporciona insights inmediatos sobre el rendimiento del sistema.",
    "El sistema de gestión de la cadena de suministro mejora la visibilidad y la eficiencia de la cadena de suministro.",
    "La herramienta de análisis predictivo utiliza algoritmos para prever eventos futuros y tomar decisiones informadas.",
    "El sistema de gestión de la cadena de suministro garantiza la disponibilidad y la eficiencia de los recursos.",
    "La tecnología de realidad aumentada mejora la interacción del usuario con el entorno físico mediante la superposición de información digital.",
    "El sistema de análisis de datos proporciona insights accionables para optimizar las operaciones empresariales.",
    "La herramienta de gestión de proyectos facilita la colaboración y la coordinación de equipos en proyectos complejos.",
    "El sistema de gestión de la cadena de suministro optimiza la planificación y la ejecución de la cadena de suministro.",
    "La tecnología de reconocimiento facial identifica y verifica la identidad de personas mediante el análisis de imágenes faciales.",
    "El sistema de análisis de datos en tiempo real proporciona insights inmediatos sobre el rendimiento del negocio.",
    "La herramienta de gestión de datos ofrece capacidades de almacenamiento, organización y acceso de datos.",
    "El sistema de gestión de la cadena de suministro garantiza la disponibilidad y la eficiencia de los recursos y materiales.",
    "La tecnología de análisis de sentimientos analiza el contenido digital para comprender las opiniones y emociones de los usuarios.",
    "El sistema de gestión de la experiencia del cliente mejora la satisfacción y la fidelidad del cliente mediante la personalización de las interacciones.",
    "La herramienta de gestión de proyectos facilita la planificación, el seguimiento y la colaboración en proyectos empresariales.",
    "El sistema de análisis de datos proporciona insights accionables para optimizar las estrategias de marketing y ventas.",
    "La tecnología de reconocimiento de voz permite la interacción con dispositivos mediante comandos de voz.",
    "El sistema de gestión de inventario optimiza el seguimiento y la gestión de productos y materiales en almacenes y centros de distribución.",
    "La herramienta de análisis de datos ofrece insights accionables para mejorar la eficiencia operativa y reducir costos.",
    "El sistema de gestión de flotas optimiza la planificación y el seguimiento de vehículos y activos móviles en tiempo real.",
    "La tecnología de análisis de datos en tiempo real proporciona insights inmediatos sobre el rendimiento y la operación de sistemas empresariales.",
    "El sistema de gestión de la cadena de suministro mejora la visibilidad y la eficiencia de la cadena de suministro.",
    "La herramienta de análisis predictivo utiliza modelos estadísticos para prever eventos futuros y tomar decisiones informadas.",
    "El sistema de gestión de la cadena de suministro garantiza la disponibilidad y la eficiencia de los recursos y materiales.",
    "La tecnología de realidad aumentada mejora la interacción del usuario con el entorno físico mediante la superposición de información digital.",
    "El sistema de análisis de datos proporciona insights accionables para optimizar las operaciones empresariales.",
    "La herramienta de gestión de proyectos facilita la colaboración y la coordinación de equipos en proyectos complejos.",
    "El sistema de gestión de la cadena de suministro optimiza la planificación y la ejecución de la cadena de suministro.",
    "La tecnología de reconocimiento facial identifica y verifica la identidad de personas mediante el análisis de imágenes faciales.",
    "El sistema de análisis de datos en tiempo real proporciona insights inmediatos sobre el rendimiento del negocio.",
    "La herramienta de gestión de datos ofrece capacidades de almacenamiento, organización y acceso de datos.",
    "El sistema de gestión de la cadena de suministro garantiza la disponibilidad y la eficiencia de los recursos y materiales.",
    "La tecnología de análisis de sentimientos analiza el contenido digital para comprender las opiniones y emociones de los usuarios.",
    "El sistema de gestión de la experiencia del cliente mejora la satisfacción y la fidelidad del cliente mediante la personalización de las interacciones.",
    "La herramienta de gestión de proyectos facilita la planificación, el seguimiento y la colaboración en proyectos empresariales.",
    "El sistema de análisis de datos proporciona insights accionables para optimizar las estrategias de marketing y ventas.",
    "La tecnología de reconocimiento de voz permite la interacción con dispositivos mediante comandos de voz.",
    "El sistema de gestión de inventario optimiza el seguimiento y la gestión de productos y materiales en almacenes y centros de distribución.",
    "La herramienta de análisis de datos ofrece insights accionables para mejorar la eficiencia operativa y reducir costos.",
    "El sistema de gestión de flotas optimiza la planificación y el seguimiento de vehículos y activos móviles en tiempo real.",
    "La tecnología de análisis de datos en tiempo real proporciona insights inmediatos sobre el rendimiento y la operación de sistemas empresariales.",
    "El sistema de gestión de la cadena de suministro mejora la visibilidad y la eficiencia de la cadena de suministro.",
    "La herramienta de análisis predictivo utiliza modelos estadísticos para prever eventos futuros y tomar decisiones informadas.",
    "El sistema de gestión de la cadena de suministro garantiza la disponibilidad y la eficiencia de los recursos y materiales.",
    "La tecnología de realidad aumentada mejora la interacción del usuario con el entorno físico mediante la superposición de información digital.",
    "El sistema de análisis de datos proporciona insights accionables para optimizar las operaciones empresariales.",
    "La herramienta de gestión de proyectos facilita la colaboración y la coordinación de equipos en proyectos complejos.",
    "El sistema de gestión de la cadena de suministro optimiza la planificación y la ejecución de la cadena de suministro.",
    "La tecnología de reconocimiento facial identifica y verifica la identidad de personas mediante el análisis de imágenes faciales.",
    "El sistema de análisis de datos en tiempo real proporciona insights inmediatos sobre el rendimiento del negocio.",
    "La herramienta de gestión de datos ofrece capacidades de almacenamiento, organización y acceso de datos.",
    "El sistema de gestión de la cadena de suministro garantiza la disponibilidad y la eficiencia de los recursos y materiales.",
    "La tecnología de análisis de sentimientos analiza el contenido digital para comprender las opiniones y emociones de los usuarios.",
    "El sistema de gestión de la experiencia del cliente mejora la satisfacción y la fidelidad del cliente mediante la personalización de las interacciones.",
    "La herramienta de gestión de proyectos facilita la planificación, el seguimiento y la colaboración en proyectos empresariales.",
    "El sistema de análisis de datos proporciona insights accionables para optimizar las estrategias de marketing y ventas.",
    "La tecnología de reconocimiento de voz permite la interacción con dispositivos mediante comandos de voz.",
    "El sistema de gestión de inventario optimiza el seguimiento y la gestión de productos y materiales en almacenes y centros de distribución.",
    "La herramienta de análisis de datos ofrece insights accionables para mejorar la eficiencia operativa y reducir costos.",
    "El sistema de gestión de flotas optimiza la planificación y el seguimiento de vehículos y activos móviles en tiempo real.",
    "La tecnología de análisis de datos en tiempo real proporciona insights inmediatos sobre el rendimiento y la operación de sistemas empresariales.",
    "El sistema de gestión de la cadena de suministro mejora la visibilidad y la eficiencia de la cadena de suministro.",
    "La herramienta de análisis predictivo utiliza modelos estadísticos para prever eventos futuros y tomar decisiones informadas.",
    "El sistema de gestión de la cadena de suministro garantiza la disponibilidad y la eficiencia de los recursos y materiales.",
    "La tecnología de realidad aumentada mejora la interacción del usuario con el entorno físico mediante la superposición de información digital.",
    "El sistema de análisis de datos proporciona insights accionables para optimizar las operaciones empresariales.",
    "La herramienta de gestión de proyectos facilita la colaboración y la coordinación de equipos en proyectos complejos.",
    "El sistema de gestión de la cadena de suministro optimiza la planificación y la ejecución de la cadena de suministro.",
    "La tecnología de reconocimiento facial identifica y verifica la identidad de personas mediante el análisis de imágenes faciales.",
    "El sistema de análisis de datos en tiempo real proporciona insights inmediatos sobre el rendimiento del negocio.",
    "La herramienta de gestión de datos ofrece capacidades de almacenamiento, organización y acceso de datos.",
    "El sistema de gestión de la cadena de suministro garantiza la disponibilidad y la eficiencia de los recursos y materiales.",
    "La tecnología de análisis de sentimientos analiza el contenido digital para comprender las opiniones y emociones de los usuarios.",
    "El sistema de gestión de la experiencia del cliente mejora la satisfacción y la fidelidad del cliente mediante la personalización de las interacciones.",
    "La herramienta de gestión de proyectos facilita la planificación, el seguimiento y la colaboración en proyectos empresariales.",
    "El sistema de análisis de datos proporciona insights accionables para optimizar las estrategias de marketing y ventas.",
    "La tecnología de reconocimiento de voz permite la interacción con dispositivos mediante comandos de voz.",
    "El sistema de gestión de inventario optimiza el seguimiento y la gestión de productos y materiales en almacenes y centros de distribución.",
    "La herramienta de análisis de datos ofrece insights accionables para mejorar la eficiencia operativa y reducir costos.",
    "El sistema de gestión de flotas optimiza la planificación y el seguimiento de vehículos y activos móviles en tiempo real.",
    "La tecnología de análisis de datos en tiempo real proporciona insights inmediatos sobre el rendimiento y la operación de sistemas empresariales.",
    "El sistema de gestión de la cadena de suministro mejora la visibilidad y la eficiencia de la cadena de suministro.",
    "La herramienta de análisis predictivo utiliza modelos estadísticos para prever eventos futuros y tomar decisiones informadas.",
    "El sistema de gestión de la cadena de suministro garantiza la disponibilidad y la eficiencia de los recursos y materiales.",
    "La tecnología de realidad aumentada mejora la interacción del usuario con el entorno físico mediante la superposición de información digital.",
    "El sistema de análisis de datos proporciona insights accionables para optimizar las operaciones empresariales.",
    "La herramienta de gestión de proyectos facilita la colaboración y la coordinación de equipos en proyectos complejos.",
    "El sistema de gestión de la cadena de suministro optimiza la planificación y la ejecución de la cadena de suministro.",
    "La tecnología de reconocimiento facial identifica y verifica la identidad de personas mediante el análisis de imágenes faciales.",
    "El sistema de análisis de datos en tiempo real proporciona insights inmediatos sobre el rendimiento del negocio.",
    "La herramienta de gestión de datos ofrece capacidades de almacenamiento, organización y acceso de datos.",
    "El sistema de gestión de la cadena de suministro garantiza la disponibilidad y la eficiencia de los recursos y materiales.",
    "La tecnología de análisis de sentimientos analiza el contenido digital para comprender las opiniones y emociones de los usuarios.",
    "El sistema de gestión de la experiencia del cliente mejora la satisfacción y la fidelidad del cliente mediante la personalización de las interacciones.",
    "La herramienta de gestión de proyectos facilita la planificación, el seguimiento y la colaboración en proyectos empresariales.",
    "El sistema de análisis de datos proporciona insights accionables para optimizar las estrategias de marketing y ventas.",
    "La tecnología de reconocimiento de voz permite la interacción con dispositivos mediante comandos de voz.",
    "El sistema de gestión de inventario optimiza el seguimiento y la gestión de productos y materiales en almacenes y centros de distribución.",
    "La herramienta de análisis de datos ofrece insights accionables para mejorar la eficiencia operativa y reducir costos.",
    "El sistema de gestión de flotas optimiza la planificación y el seguimiento de vehículos y activos móviles en tiempo real.",
    "La tecnología de análisis de datos en tiempo real proporciona insights inmediatos sobre el rendimiento y la operación de sistemas empresariales.",
    "El sistema de gestión de la cadena de suministro mejora la visibilidad y la eficiencia de la cadena de suministro.",
    "La herramienta de análisis predictivo utiliza modelos estadísticos para prever eventos futuros y tomar decisiones informadas.",
    "El sistema de gestión de la cadena de suministro garantiza la disponibilidad y la eficiencia de los recursos y materiales.",
    "La tecnología de realidad aumentada mejora la interacción del usuario con el entorno físico mediante la superposición de información digital.",
    "El sistema de análisis de datos proporciona insights accionables para optimizar las operaciones empresariales.",
    "La herramienta de gestión de proyectos facilita la colaboración y la coordinación de equipos en proyectos complejos.",
    "El sistema de gestión de la cadena de suministro optimiza la planificación y la ejecución de la cadena de suministro.",
    "La tecnología de reconocimiento facial identifica y verifica la identidad de personas mediante el análisis de imágenes faciales.",
    "El sistema de análisis de datos en tiempo real proporciona insights inmediatos sobre el rendimiento del negocio.",
    "La herramienta de gestión de datos ofrece capacidades de almacenamiento, organización y acceso de datos.",
    "El sistema de gestión de la cadena de suministro garantiza la disponibilidad y la eficiencia de los recursos y materiales.",
    "La tecnología de análisis de sentimientos analiza el contenido digital para comprender las opiniones y emociones de los usuarios.",
    "El sistema de gestión de la experiencia del cliente mejora la satisfacción y la fidelidad del cliente mediante la personalización de las interacciones.",
    "La herramienta de gestión de proyectos facilita la planificación, el seguimiento y la colaboración en proyectos empresariales.",
    "El sistema de análisis de datos proporciona insights accionables para optimizar las estrategias de marketing y ventas.",
    "La tecnología de reconocimiento de voz permite la interacción con dispositivos mediante comandos de voz.",
    "El sistema de gestión de inventario optimiza el seguimiento y la gestión de productos y materiales en almacenes y centros de distribución.",
    "La herramienta de análisis de datos ofrece insights accionables para mejorar la eficiencia operativa y reducir costos.",
    "El sistema de gestión de flotas optimiza la planificación y el seguimiento de vehículos y activos móviles en tiempo real.",
    "La tecnología de análisis de datos en tiempo real proporciona insights inmediatos sobre el rendimiento y la operación de sistemas empresariales."
]

# Función para identificar el adjetivo en una oración
def identificar_adjetivo(oracion):
    palabras = oracion.split()
    for palabra in palabras:
        if palabra.lower() in adjetivos:
            return palabra.lower()
    return None

# Lista de adjetivos en Lengua Castellana
adjetivos = [
    "joven", "incómoda", "grande", "enorme", "blanco",
    "atractivo", "blanco", "atractivo", "bonita", "enorme",
    "cuero", "cocina", "italiano", "verde", "gruñona",
    "bella", "vieja", "vieja", "grandes", "gris", "fría"
    # ... Agrega más adjetivos aquí ...
]

# Procesamiento de cada oración
for i, oracion in enumerate(oraciones, 1):
    print(f"Oración {i}: {oracion}")
    adjetivo_correcto = identificar_adjetivo(oracion)
    if adjetivo_correcto:
        respuesta_usuario = input("Identifica el adjetivo en la oración: ")
        if respuesta_usuario.lower() == adjetivo_correcto:
            print("¡Correcto! Reescribe la oración en Lengua Castellana:")
            nueva_oracion = input()
            print(f"Oración reescrita: {nueva_oracion}\n")
        else:
            print(f"El adjetivo correcto era '{adjetivo_correcto}'. Inténtalo de nuevo.\n")
    else:
        print("No se encontró un adjetivo en esta oración.\n")

print("¡Has completado todas las oraciones! ¡Bien hecho!")
